"""Database schema for documentation-api-docs.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "docs": {
        "table_name": "documentation_api_docs_docs",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("slug", "TEXT NOT NULL DEFAULT ''"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("section", "TEXT NOT NULL DEFAULT ''"),
            ("order_", "INTEGER NOT NULL DEFAULT 0"),
            ("content", "TEXT NOT NULL DEFAULT ''"),
            ("updated_at", "TEXT NOT NULL DEFAULT ''"),
            ("tags", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "updated_at",
        ],
    },
    "search_index": {
        "table_name": "documentation_api_docs_search_index",
        "columns": [
            ("row_id", "INTEGER PRIMARY KEY"),
            ("doc_id", "INTEGER NOT NULL DEFAULT 0"),
            ("keywords", "TEXT NOT NULL DEFAULT ''"),
        ],
    },
    "users": {
        "table_name": "documentation_api_docs_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("api_key", "TEXT NOT NULL DEFAULT ''"),
            ("bookmarked_pages", "TEXT NOT NULL DEFAULT ''"),
            ("role", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "role",
            "root_user_id",
        ],
    },
}
