"""Database schema for handwritten-notes-whiteboards.

Auto-generated by scripts/generate_schemas.py -- edit freely.
"""

TABLES = {
    "notebooks": {
        "table_name": "handwritten_notes_whiteboards_notebooks",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("owner_id", "INTEGER NOT NULL DEFAULT 0"),
            ("color", "TEXT NOT NULL DEFAULT ''"),
            ("notes_count", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "owner_id",
        ],
    },
    "notes": {
        "table_name": "handwritten_notes_whiteboards_notes",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("content", "TEXT NOT NULL DEFAULT ''"),
            ("owner_id", "INTEGER NOT NULL DEFAULT 0"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("updated_at", "TEXT NOT NULL DEFAULT ''"),
            ("tags", "TEXT NOT NULL DEFAULT ''"),
            ("notebook_id", "INTEGER NOT NULL DEFAULT 0"),
            ("is_pinned", "INTEGER NOT NULL DEFAULT 0"),
            ("color", "TEXT NOT NULL DEFAULT ''"),
            ("drawing_data", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "created_at",
            "owner_id",
            "updated_at",
        ],
    },
    "users": {
        "table_name": "handwritten_notes_whiteboards_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("display_name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("avatar", "TEXT NOT NULL DEFAULT ''"),
        ],
    },
    "whiteboards": {
        "table_name": "handwritten_notes_whiteboards_whiteboards",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("owner_id", "INTEGER NOT NULL DEFAULT 0"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("updated_at", "TEXT NOT NULL DEFAULT ''"),
            ("shared_with", "TEXT NOT NULL DEFAULT ''"),
            ("elements", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "created_at",
            "owner_id",
            "updated_at",
        ],
    },
}
