"""Database schema for books-comics.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "books": {
        "table_name": "books_comics_books",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("author", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("subject", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("book_url", "TEXT NOT NULL DEFAULT ''"),
            ("institution", "TEXT NOT NULL DEFAULT ''"),
            ("license", "TEXT NOT NULL DEFAULT ''"),
            ("cover_url", "TEXT NOT NULL DEFAULT ''"),
            ("rating", "REAL NOT NULL DEFAULT 0.0"),
            ("price", "REAL NOT NULL DEFAULT 0.0"),
            ("year", "INTEGER NOT NULL DEFAULT 0"),
            ("num_chapters", "INTEGER NOT NULL DEFAULT 0"),
            ("chapters", "TEXT NOT NULL DEFAULT '[]'"),
        ],
        "indexes": [
            "category",
            "author",
            "year",
        ],
    },
    "cart": {
        "table_name": "books_comics_cart",
        "columns": [
            ("row_id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("items", "TEXT NOT NULL DEFAULT ''"),
            ("subtotal", "REAL NOT NULL DEFAULT 0.0"),
            ("estimated_tax", "REAL NOT NULL DEFAULT 0.0"),
            ("total", "REAL NOT NULL DEFAULT 0.0"),
        ],
        "indexes": [
            "user_id",
        ],
    },
    "orders": {
        # Purchase / order history — created + registered at runtime on first use
        # (see routes._ensure_orders_table, the forums_messages seed convention).
        # Records each checkout as a receipt (book/date/price/order id), distinct
        # from the reading library. Session orders live in the overlay.
        "table_name": "books_comics_orders",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("order_number", "TEXT NOT NULL DEFAULT ''"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("items", "TEXT NOT NULL DEFAULT '[]'"),
            ("item_count", "INTEGER NOT NULL DEFAULT 0"),
            ("subtotal", "REAL NOT NULL DEFAULT 0.0"),
            ("total", "REAL NOT NULL DEFAULT 0.0"),
            ("payment_method", "TEXT NOT NULL DEFAULT ''"),
            ("card_last4", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("status", "TEXT NOT NULL DEFAULT 'completed'"),
        ],
        "indexes": [
            "user_id",
        ],
    },
    "categories": {
        "table_name": "books_comics_categories",
        "columns": [
            ("slug", "TEXT PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
        ],
    },
    "reviews": {
        "table_name": "books_comics_reviews",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("book_id", "INTEGER NOT NULL DEFAULT 0"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("rating", "INTEGER NOT NULL DEFAULT 0"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("body", "TEXT NOT NULL DEFAULT ''"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("helpful_count", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "date",
            "user_id",
        ],
    },
    "users": {
        "table_name": "books_comics_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("saved_books", "TEXT NOT NULL DEFAULT ''"),
            ("followed_authors", "TEXT NOT NULL DEFAULT ''"),
            ("subscriptions", "TEXT NOT NULL DEFAULT ''"),
            ("reading_list", "TEXT NOT NULL DEFAULT ''"),
            ("dismissed_issues", "TEXT NOT NULL DEFAULT ''"),
            ("cart", "TEXT NOT NULL DEFAULT ''"),
            ("avatar", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "root_user_id",
        ],
    },
}
