"""Database schema for software-marketplace.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "app_reviews": {
        "table_name": "software_marketplace_app_reviews",
        "columns": [
            ("row_id", "INTEGER PRIMARY KEY"),
            ("app", "TEXT NOT NULL DEFAULT ''"),
            ("translated_review", "TEXT NOT NULL DEFAULT ''"),
            ("sentiment", "TEXT NOT NULL DEFAULT ''"),
            ("sentiment_polarity", "REAL NOT NULL DEFAULT 0.0"),
            ("sentiment_subjectivity", "REAL NOT NULL DEFAULT 0.0"),
        ],
    },
    "apps": {
        "table_name": "software_marketplace_apps",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("rating", "REAL NOT NULL DEFAULT 0.0"),
            ("reviews_count", "INTEGER NOT NULL DEFAULT 0"),
            ("size", "TEXT NOT NULL DEFAULT ''"),
            ("installs", "TEXT NOT NULL DEFAULT ''"),
            ("price", "REAL NOT NULL DEFAULT 0.0"),
            ("content_rating", "TEXT NOT NULL DEFAULT ''"),
            ("genre", "TEXT NOT NULL DEFAULT ''"),
            ("developer", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("last_updated", "TEXT NOT NULL DEFAULT ''"),
            ("app", "TEXT NOT NULL DEFAULT ''"),
            ("reviews", "INTEGER NOT NULL DEFAULT 0"),
            ("type", "TEXT NOT NULL DEFAULT ''"),
            ("genres", "TEXT NOT NULL DEFAULT ''"),
            ("current_ver", "TEXT NOT NULL DEFAULT ''"),
            ("android_ver", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "category",
            "genre",
            "type",
        ],
    },
    "cart": {
        "table_name": "software_marketplace_cart",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("app_id", "INTEGER NOT NULL DEFAULT 0"),
            ("added_date", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "user_id",
        ],
    },
    "installed": {
        "table_name": "software_marketplace_installed",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("app_id", "INTEGER NOT NULL DEFAULT 0"),
            ("installed_date", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "user_id",
        ],
    },
    "purchases": {
        "table_name": "software_marketplace_purchases",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("app_id", "INTEGER NOT NULL DEFAULT 0"),
            ("app_name", "TEXT NOT NULL DEFAULT ''"),
            ("price", "REAL NOT NULL DEFAULT 0.0"),
            ("discount", "REAL NOT NULL DEFAULT 0.0"),
            ("promo_code", "TEXT"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("receipt_id", "TEXT NOT NULL DEFAULT ''"),
            ("status", "TEXT NOT NULL DEFAULT 'completed'"),
            ("refund_date", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "user_id",
        ],
    },
    "promo_codes": {
        "table_name": "software_marketplace_promo_codes",
        "columns": [
            ("row_id", "INTEGER PRIMARY KEY"),
            ("code", "TEXT NOT NULL DEFAULT ''"),
            ("discount_percent", "INTEGER NOT NULL DEFAULT 0"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("active", "INTEGER NOT NULL DEFAULT 0"),
            ("max_uses", "INTEGER NOT NULL DEFAULT 0"),
            ("uses", "INTEGER NOT NULL DEFAULT 0"),
        ],
    },
    "reviews": {
        "table_name": "software_marketplace_reviews",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("app_id", "INTEGER NOT NULL DEFAULT 0"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("rating", "INTEGER NOT NULL DEFAULT 0"),
            ("text", "TEXT NOT NULL DEFAULT ''"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("helpful_count", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "date",
            "user_id",
        ],
    },
    "settings": {
        "table_name": "software_marketplace_settings",
        "columns": [
            ("row_id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("theme", "TEXT NOT NULL DEFAULT ''"),
            ("language", "TEXT NOT NULL DEFAULT ''"),
            ("auto_update", "INTEGER NOT NULL DEFAULT 0"),
            ("notification_frequency", "INTEGER NOT NULL DEFAULT 0"),
            ("download_wifi_only", "INTEGER NOT NULL DEFAULT 0"),
            ("content_filter", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "user_id",
        ],
    },
    "users": {
        "table_name": "software_marketplace_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("display_name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
        ],
    },
    "wishlists": {
        "table_name": "software_marketplace_wishlists",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("app_id", "INTEGER NOT NULL DEFAULT 0"),
            ("added_date", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "user_id",
        ],
    },
}
