"""Database schema for calendar-todo.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "events": {
        "table_name": "calendar_todo_events",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("calendar", "TEXT NOT NULL DEFAULT ''"),
            ("start", "TEXT NOT NULL DEFAULT ''"),
            ("end_", "TEXT NOT NULL DEFAULT ''"),
            ("all_day", "INTEGER NOT NULL DEFAULT 0"),
            ("location", "TEXT NOT NULL DEFAULT ''"),
            ("recurring", "TEXT NOT NULL DEFAULT ''"),
            ("reminder_minutes", "INTEGER NOT NULL DEFAULT 0"),
            ("priority", "TEXT NOT NULL DEFAULT ''"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
            ("attendees", "TEXT NOT NULL DEFAULT ''"),
            ("color", "TEXT NOT NULL DEFAULT ''"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "category",
            "created_at",
            "status",
            "user_id",
        ],
    },
    "users": {
        "table_name": "calendar_todo_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("calendars", "TEXT NOT NULL DEFAULT ''"),
            ("shared_calendars", "TEXT NOT NULL DEFAULT ''"),
            ("settings", "TEXT NOT NULL DEFAULT ''"),
            ("avatar", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "root_user_id",
        ],
    },
}
