"""Database schema for visual-how-to-guides.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "bookmarks": {
        "table_name": "visual_how_to_guides_bookmarks",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("guide_id", "INTEGER NOT NULL DEFAULT 0"),
            ("bookmarked_at", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "user_id",
        ],
    },
    "categories": {
        "table_name": "visual_how_to_guides_categories",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("guide_count", "INTEGER NOT NULL DEFAULT 0"),
        ],
    },
    "comments": {
        "table_name": "visual_how_to_guides_comments",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("guide_id", "INTEGER NOT NULL DEFAULT 0"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("text", "TEXT NOT NULL DEFAULT ''"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("helpful_count", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "date",
            "user_id",
        ],
    },
    "guides": {
        "table_name": "visual_how_to_guides_guides",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("author_id", "INTEGER NOT NULL DEFAULT 0"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("updated_at", "TEXT NOT NULL DEFAULT ''"),
            ("difficulty", "TEXT NOT NULL DEFAULT ''"),
            ("duration_minutes", "INTEGER NOT NULL DEFAULT 0"),
            ("views", "INTEGER NOT NULL DEFAULT 0"),
            ("rating", "REAL NOT NULL DEFAULT 0.0"),
            ("steps", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "author_id",
            "category",
            "created_at",
            "updated_at",
        ],
    },
    "users": {
        "table_name": "visual_how_to_guides_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("display_name", "TEXT NOT NULL DEFAULT ''"),
            ("bio", "TEXT NOT NULL DEFAULT ''"),
            ("avatar", "TEXT NOT NULL DEFAULT ''"),
            ("joined_at", "TEXT NOT NULL DEFAULT ''"),
        ],
    },
}
