"""Database schema for weather.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "alerts": {
        "table_name": "weather_alerts",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("type", "TEXT NOT NULL DEFAULT ''"),
            ("severity", "TEXT NOT NULL DEFAULT ''"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("start", "TEXT NOT NULL DEFAULT ''"),
            ("end_", "TEXT NOT NULL DEFAULT ''"),
            ("areas", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "type",
        ],
    },
    "current": {
        "table_name": "weather_current",
        "columns": [
            ("row_id", "INTEGER PRIMARY KEY"),
            ("location", "TEXT NOT NULL DEFAULT ''"),
            ("temp_f", "INTEGER NOT NULL DEFAULT 0"),
            ("temp_c", "INTEGER NOT NULL DEFAULT 0"),
            ("humidity", "INTEGER NOT NULL DEFAULT 0"),
            ("wind_mph", "INTEGER NOT NULL DEFAULT 0"),
            ("wind_dir", "TEXT NOT NULL DEFAULT ''"),
            ("conditions", "TEXT NOT NULL DEFAULT ''"),
            ("uv_index", "INTEGER NOT NULL DEFAULT 0"),
            ("air_quality", "TEXT NOT NULL DEFAULT ''"),
            ("feels_like_f", "INTEGER NOT NULL DEFAULT 0"),
            ("visibility_mi", "INTEGER NOT NULL DEFAULT 0"),
            ("pressure_inhg", "REAL NOT NULL DEFAULT 0.0"),
            ("updated", "TEXT NOT NULL DEFAULT ''"),
        ],
    },
    "forecast": {
        "table_name": "weather_forecast",
        "columns": [
            ("row_id", "INTEGER PRIMARY KEY"),
            ("day", "TEXT NOT NULL DEFAULT ''"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("high_f", "INTEGER NOT NULL DEFAULT 0"),
            ("low_f", "INTEGER NOT NULL DEFAULT 0"),
            ("conditions", "TEXT NOT NULL DEFAULT ''"),
            ("precip_pct", "INTEGER NOT NULL DEFAULT 0"),
            ("wind_mph", "INTEGER NOT NULL DEFAULT 0"),
            ("humidity", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "date",
        ],
    },
    "historical": {
        "table_name": "weather_historical",
        "columns": [
            ("row_id", "INTEGER PRIMARY KEY"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("high_f", "INTEGER NOT NULL DEFAULT 0"),
            ("low_f", "INTEGER NOT NULL DEFAULT 0"),
            ("avg_temp_f", "INTEGER NOT NULL DEFAULT 0"),
            ("precip_in", "REAL NOT NULL DEFAULT 0.0"),
            ("conditions", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "date",
        ],
    },
    "hourly": {
        "table_name": "weather_hourly",
        "columns": [
            ("row_id", "INTEGER PRIMARY KEY"),
            ("hour", "TEXT NOT NULL DEFAULT ''"),
            ("temp_f", "INTEGER NOT NULL DEFAULT 0"),
            ("conditions", "TEXT NOT NULL DEFAULT ''"),
            ("precip_pct", "INTEGER NOT NULL DEFAULT 0"),
            ("wind_mph", "INTEGER NOT NULL DEFAULT 0"),
            ("humidity", "INTEGER NOT NULL DEFAULT 0"),
        ],
    },
    "locations": {
        "table_name": "weather_locations",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("lat", "REAL NOT NULL DEFAULT 0.0"),
            ("lng", "REAL NOT NULL DEFAULT 0.0"),
            ("is_default", "INTEGER NOT NULL DEFAULT 0"),
        ],
    },
    "users": {
        "table_name": "weather_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("default_location", "INTEGER NOT NULL DEFAULT 0"),
            ("saved_locations", "TEXT NOT NULL DEFAULT ''"),
        ],
    },
}
