"""Database schema for university-academic.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "alumni": {
        "table_name": "university_academic_alumni",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("graduation_year", "INTEGER NOT NULL DEFAULT 0"),
            ("degree", "TEXT NOT NULL DEFAULT ''"),
            ("advisor", "TEXT NOT NULL DEFAULT ''"),
            ("senior_project", "TEXT NOT NULL DEFAULT ''"),
            ("current_position", "TEXT NOT NULL DEFAULT ''"),
            ("linkedin", "TEXT NOT NULL DEFAULT ''"),
            ("notable_achievements", "TEXT NOT NULL DEFAULT ''"),
            ("alumni_donor", "INTEGER NOT NULL DEFAULT 0"),
            ("last_event_attended", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "root_user_id",
        ],
    },
    "courses": {
        "table_name": "university_academic_courses",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("code", "TEXT NOT NULL DEFAULT ''"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("credits", "INTEGER NOT NULL DEFAULT 0"),
            ("level", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("prerequisites", "TEXT NOT NULL DEFAULT ''"),
            ("instructor", "TEXT NOT NULL DEFAULT ''"),
            ("quarters_offered", "TEXT NOT NULL DEFAULT ''"),
            ("max_enrollment", "INTEGER NOT NULL DEFAULT 0"),
            ("research_area", "TEXT NOT NULL DEFAULT ''"),
        ],
    },
    "departments": {
        "table_name": "university_academic_departments",
        "columns": [
            ("row_id", "INTEGER PRIMARY KEY"),
            ("department", "TEXT NOT NULL DEFAULT ''"),
            ("research_areas", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "department",
        ],
    },
    "events": {
        "table_name": "university_academic_events",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("type", "TEXT NOT NULL DEFAULT ''"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("time", "TEXT NOT NULL DEFAULT ''"),
            ("location", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("organizer", "TEXT NOT NULL DEFAULT ''"),
            ("registration_required", "INTEGER NOT NULL DEFAULT 0"),
            ("attendee_count", "INTEGER NOT NULL DEFAULT 0"),
            ("companies_attending", "TEXT NOT NULL DEFAULT ''"),
            ("tags", "TEXT NOT NULL DEFAULT ''"),
            ("end_date", "TEXT NOT NULL DEFAULT ''"),
            ("sponsors", "TEXT NOT NULL DEFAULT ''"),
            ("featured_speaker", "TEXT NOT NULL DEFAULT ''"),
            ("speaker", "TEXT NOT NULL DEFAULT ''"),
            ("keynote", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "date",
            "type",
        ],
    },
    "faculty": {
        "table_name": "university_academic_faculty",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("office", "TEXT NOT NULL DEFAULT ''"),
            ("phone", "TEXT NOT NULL DEFAULT ''"),
            ("research_areas", "TEXT NOT NULL DEFAULT ''"),
            ("bio", "TEXT NOT NULL DEFAULT ''"),
            ("publications_count", "INTEGER NOT NULL DEFAULT 0"),
            ("joined_year", "INTEGER NOT NULL DEFAULT 0"),
            ("homepage", "TEXT NOT NULL DEFAULT ''"),
        ],
    },
    "users": {
        "table_name": "university_academic_users",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("net_id", "TEXT NOT NULL DEFAULT ''"),
            ("display_name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("role", "TEXT NOT NULL DEFAULT ''"),
            ("degree", "TEXT NOT NULL DEFAULT ''"),
            ("graduation_year", "INTEGER NOT NULL DEFAULT 0"),
            ("enrolled_year", "INTEGER NOT NULL DEFAULT 0"),
            ("advisor", "TEXT NOT NULL DEFAULT ''"),
            ("honors", "TEXT NOT NULL DEFAULT ''"),
            ("last_login", "TEXT NOT NULL DEFAULT ''"),
            ("affiliation", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "role",
            "root_user_id",
        ],
    },
}
