"""Database schema for spreadsheets-slides.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "presentations": {
        "table_name": "spreadsheets_slides_presentations",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("owner_id", "INTEGER NOT NULL DEFAULT 0"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("updated_at", "TEXT NOT NULL DEFAULT ''"),
            ("shared_with", "TEXT NOT NULL DEFAULT ''"),
            ("slides_count", "INTEGER NOT NULL DEFAULT 0"),
            ("slides", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "created_at",
            "owner_id",
            "updated_at",
        ],
    },
    "spreadsheets": {
        "table_name": "spreadsheets_slides_spreadsheets",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("owner_id", "INTEGER NOT NULL DEFAULT 0"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("updated_at", "TEXT NOT NULL DEFAULT ''"),
            ("shared_with", "TEXT NOT NULL DEFAULT ''"),
            ("rows", "INTEGER NOT NULL DEFAULT 0"),
            ("cols", "INTEGER NOT NULL DEFAULT 0"),
            ("sheets", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "created_at",
            "owner_id",
            "updated_at",
        ],
    },
    "templates_ss": {
        "table_name": "spreadsheets_slides_templates_ss",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("type", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "category",
            "type",
        ],
    },
    "users": {
        "table_name": "spreadsheets_slides_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("avatar_color", "TEXT NOT NULL DEFAULT ''"),
            ("role", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "role",
        ],
    },
}
