"""Database schema for dictionaries-language-tools.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "entries": {
        "table_name": "dictionaries_language_tools_entries",
        "columns": [
            ("senses", "TEXT NOT NULL DEFAULT ''"),
            ("pos", "TEXT NOT NULL DEFAULT ''"),
            ("head_templates", "TEXT NOT NULL DEFAULT ''"),
            ("categories", "TEXT NOT NULL DEFAULT ''"),
            ("forms", "TEXT NOT NULL DEFAULT ''"),
            ("hyponyms", "TEXT NOT NULL DEFAULT ''"),
            ("derived", "TEXT NOT NULL DEFAULT ''"),
            ("related", "TEXT NOT NULL DEFAULT ''"),
            ("descendants", "TEXT NOT NULL DEFAULT ''"),
            ("translations", "TEXT NOT NULL DEFAULT ''"),
            ("etymology_text", "TEXT NOT NULL DEFAULT ''"),
            ("etymology_templates", "TEXT NOT NULL DEFAULT ''"),
            ("sounds", "TEXT NOT NULL DEFAULT ''"),
            ("hyphenations", "TEXT NOT NULL DEFAULT ''"),
            ("word", "TEXT PRIMARY KEY"),
            ("lang", "TEXT NOT NULL DEFAULT ''"),
            ("lang_code", "TEXT NOT NULL DEFAULT ''"),
            ("synonyms", "TEXT NOT NULL DEFAULT ''"),
            ("hypernyms", "TEXT NOT NULL DEFAULT ''"),
            ("coordinate_terms", "TEXT NOT NULL DEFAULT ''"),
            ("meronyms", "TEXT NOT NULL DEFAULT ''"),
            ("antonyms", "TEXT NOT NULL DEFAULT ''"),
            ("etymology_number", "TEXT NOT NULL DEFAULT ''"),
            ("inflection_templates", "TEXT NOT NULL DEFAULT ''"),
            ("wikipedia", "TEXT NOT NULL DEFAULT ''"),
            ("hyphenation", "TEXT NOT NULL DEFAULT ''"),
            ("holonyms", "TEXT NOT NULL DEFAULT ''"),
        ],
    },
    "users": {
        "table_name": "dictionaries_language_tools_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("saved_words", "TEXT NOT NULL DEFAULT ''"),
            ("vocabulary_lists", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "root_user_id",
        ],
    },
}
