"""Write the supplement's generated LaTeX: the primitive and operation tables and the website gallery.

    python docs/figures/supp/make_supp.py [--config docs/figures/supp/supp_config.yaml]

Outputs (in out_dir): supp_primitives.tex, supp_ops.tex, supp_gallery.tex. Screenshots are copied into the paper's
figures/sites and figures/annotation folders. Read-only on the data: task.json files, the macro registry, the site
READMEs and the generated-trajectory index.
"""
import argparse, collections, glob, json, os, re, shutil, sys
import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(HERE, "..", "sites"))
sys.path.insert(0, os.path.join(HERE, "..", "common"))
from results import MIN_INSTANCES, well_covered  # noqa: E402  the paper's primitive set, shared with every figure

TEX = {"&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}",
       "^": r"\textasciicircum{}", "\\": r"\textbackslash{}", "→": r"$\rightarrow$", "←": r"$\leftarrow$", "…": r"\dots{}",
       "—": "---", "–": "--", "“": "``", "”": "''", "‘": "`", "’": "'", "×": r"$\times$", "·": r"$\cdot$", "≥": r"$\geq$",
       "≤": r"$\leq$", "é": r"\'e", "°": r"$^\circ$", "≈": r"$\approx$", "\u00a0": "~"}


def esc(s):
    out = "".join(TEX.get(c, c) for c in str(s))
    bad = {c for c in out if ord(c) > 127}
    if bad:
        print("  warning: non-ASCII left as is:", "".join(sorted(bad)), "in", s[:60])
    return out


def human_tasks():
    return [json.load(open(f)) for f in glob.glob(os.path.join(ROOT, "data", "annotations", "*", "*", "task.json"))]


def primitives(cfg, reg, tasks):
    from datagen.viewer import FAMILIES, _kept_rows
    inst, sites = collections.Counter(), collections.defaultdict(set)
    for t in tasks:
        for g in t["macro_tags"]:
            if g.get("required", True):
                inst[g["macro"]] += 1
                sites[g["macro"]].add(t["site"])
    # the training pool: kept trajectories that were replayed into the agent harness (base episodes only, not the
    # chain/recovery variants made from them); the answer-reporting primitives are trained from base-model replays
    pool = {n for n in os.listdir(os.path.join(ROOT, cfg["pool_dir"])) if "~" not in n}
    kept = collections.Counter(r["macro"] for k, r in _kept_rows().items() if k in pool)
    print(f"  training pool: {sum(kept.values())} generated trajectories")
    keep, names = well_covered(), cfg.get("family_names") or {}
    rows, dropped = [], []
    for fam, ms in FAMILIES.items():
        shown = [m for m in ms if m in keep]
        dropped += [m for m in ms if m not in keep]
        if not shown:
            continue
        rows.append(f"\\multicolumn{{5}}{{@{{}}l}}{{\\textit{{{esc(names.get(fam, fam))}}}}} \\\\")
        for m in sorted(shown, key=lambda m: -inst[m]):
            e = reg[m]
            d = esc(e["description"].rstrip("."))
            if e.get("span_start") and e.get("span_end"):
                d += f". \\emph{{Span:}} {esc(e['span_start'])} $\\rightarrow$ {esc(e['span_end'])}"
            rows.append(f"\\texttt{{{esc(m)}}} & {d} & {inst[m]} & {len(sites[m])} & {kept[m] or '--'} \\\\")
    n_shown = sum(len(FAMILIES[f]) for f in FAMILIES) - len(dropped)
    drop_txt = ", ".join(f"\\texttt{{{esc(m)}}} ({inst[m]})" for m in sorted(dropped, key=lambda m: (-inst[m], m)))
    gen_kept = sum(kept[m] for m in keep)
    caption = (f"\\textbf{{The {n_shown} interaction primitives}}, by skill family. "
               f"\\emph{{Tasks}}: instances in the 376 human tasks; \\emph{{Sites}}: sites those tasks use; "
               f"\\emph{{Gen.}}: trajectories generated by \\miniwebgen{{}} in the training pool ({gen_kept:,}; the pool's "
               f"other {sum(kept.values()) - gen_kept:,} are of dropped primitives, and \\texttt{{report\\_information}} is "
               f"learned from the base model's own successes instead). The span marks where an instance starts and ends in "
               f"a demonstration. Dropped in the final refinement (fewer than {MIN_INSTANCES} human-task instances): "
               f"{drop_txt}. \\textbf{{Takeaway:}} each primitive recurs in at least {MIN_INSTANCES} human tasks, and all but "
               f"\\texttt{{report\\_information}} get generated practice.")
    return "\n".join([
        "% generated by docs/figures/supp/make_supp.py; do not edit by hand",
        "{\\footnotesize\\setlength{\\tabcolsep}{4pt}",
        "\\begin{longtable}{@{}p{0.235\\linewidth}p{0.565\\linewidth}rrr@{}}",
        f"\\caption{{{caption}}}\\label{{tab:supp-primitives}}\\\\",
        "\\toprule Primitive & Description & Tasks & Sites & Gen. \\\\ \\midrule \\endfirsthead",
        "\\toprule Primitive & Description & Tasks & Sites & Gen. \\\\ \\midrule \\endhead",
        "\\bottomrule \\endlastfoot", *rows, "\\end{longtable}}", ""])


def operations(cfg, reg, tasks):
    keep = well_covered()                               # operations on instances of the reported primitives only
    ops = collections.Counter(g["op"] for t in tasks for g in t["macro_tags"]
                              if g.get("required", True) and g.get("op") and g["macro"] in keep)
    lo = cfg["min_instances"]
    defs = reg["operations"]
    shown = [o for o in defs if ops[o] >= lo]
    dropped = [o for o in defs if ops[o] < lo]
    rows = []
    for o in sorted(shown, key=lambda o: -ops[o]):
        d = defs[o]["desc"]
        d = d.split(": ", 1)[1] if d.lower().startswith(o + "/") or d.lower().startswith(o + ":") else d
        d = re.sub(r"\s*\(baseline / filler\)", "", d)           # registry note for annotators, not a definition
        rows.append(f"\\texttt{{{o}}} & {esc(d)} & {esc(defs[o].get('check', ''))} & {ops[o]} \\\\")
    drop_txt = ", ".join(f"\\texttt{{{o}}} ({ops[o]})" for o in sorted(dropped, key=lambda o: -ops[o]))
    caption = (f"\\textbf{{Reasoning operations}} attached to instances of the {len(keep)} primitives in the human tasks. A primitive "
               f"without an operation is a pure interaction. Not listed (fewer than {lo} instances): {drop_txt}. "
               f"\\textbf{{Takeaway:}} most reasoning reads one value; counting and finding extrema are rarer, and harder.")
    return "\n".join([
        "% generated by docs/figures/supp/make_supp.py; do not edit by hand",
        "\\begin{table}[h]", "\\centering", "\\footnotesize", "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{@{}lp{0.42\\linewidth}p{0.36\\linewidth}r@{}}", "\\toprule",
        "Operation & Definition & Check & Instances \\\\", "\\midrule", *rows, "\\bottomrule", "\\end{tabular}",
        f"\\caption{{{caption}}}", "\\label{tab:supp-ops}", "\\end{table}", ""])


# notes in the site READMEs meant for developers, not readers of the paper
README_NOTES = [r' \(listed as "[^"]*" in `site\.json`\)', r" The UI brand is \w+; `site\.json` names the site \"[^\"]*\"\.",
                r" \(`im-u\d+`\)", r"(?<=shared) MiniWeb(?= persona)"]


def readme(site):
    t = open(os.path.join(ROOT, "sites", site, "doc", "README.md")).read().split("\n")
    m = re.match(r"# (.+?) \(`([^`]+)`\)", t[0])
    d = " ".join("\n".join(t[1:]).strip().split("\n\n")[0].split())
    for r in README_NOTES:
        d = re.sub(r, "", d)
    return m.group(1), d


def esc_code(s):
    """esc() plus `code` spans as \\texttt."""
    return re.sub(r"`([^`]+)`", r"\\texttt{\1}", esc(s))


def gallery(cfg, tasks, figdir):
    import importlib.util
    spec = importlib.util.spec_from_file_location("ms", os.path.join(HERE, "..", "sites", "make_sites.py"))
    src = open(spec.origin).read()
    ns = {}                                            # only the module's constants, not its drawing code
    head = src[:src.index("def name(s):")]
    exec(compile(head, spec.origin, "exec"), {"__file__": spec.origin, "__name__": "ms"}, ns)
    domains, dataset, held = ns["DOMAINS"], ns["DATASET"], ns["HELD_OUT"]
    ntask = collections.Counter(s for t in tasks for s in set(t.get("sites") or [t["site"]]))
    loc = yaml.safe_load(open(os.path.join(ROOT, "data", "macro_locations.yaml")))
    keep = well_covered()
    os.makedirs(os.path.join(figdir, "sites"), exist_ok=True)
    cells = []
    for dom, _, ss in domains:
        for s in ss:
            shutil.copy(os.path.join(ROOT, cfg["shots"], f"{s}.jpg"), os.path.join(figdir, "sites", f"{s}.jpg"))
            name, desc = readme(s)
            meta = [f"\\texttt{{{esc(s)}}}", esc(dom), "\\textbf{held-out}" if s in held else "train",
                    "data: " + esc(dataset[s]) if s in dataset else "synthetic data",
                    f"{ntask[s]} tasks", f"{len(set(loc.get(s) or {}) & keep)} primitives"]
            cells.append("\n".join([
                "\\begin{minipage}[t]{0.32\\linewidth}\\raggedright",
                f"\\includegraphics[width=\\linewidth]{{sites/{s}.jpg}}\\\\[1pt]",
                f"{{\\small\\textbf{{{esc(name)}}}}}\\\\",
                "{\\scriptsize\\color{black!65} " + " $\\cdot$ ".join(meta) + "}\\\\[1pt]",
                f"{{\\scriptsize {esc_code(desc)}}}",
                "\\end{minipage}"]))
    n = cfg["per_row"]
    rows = ["\\hfill".join(cells[i:i + n]) + ("\\hfill\\mbox{}" * (n - len(cells[i:i + n]))) for i in range(0, len(cells), n)]
    return ("% generated by docs/figures/supp/make_supp.py; do not edit by hand\n\\noindent\n"
            + "\n\\par\\bigskip\\noindent\n".join(rows) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=os.path.join(HERE, "supp_config.yaml"))
    cfg = yaml.safe_load(open(ap.parse_args().config))
    reg = yaml.safe_load(open(os.path.join(ROOT, "data", "macros.yaml")))
    tasks = human_tasks()
    out, figdir = os.path.join(ROOT, cfg["out_dir"]), os.path.join(ROOT, cfg["figures_dir"])
    os.makedirs(out, exist_ok=True)
    files = {"supp_primitives.tex": primitives(cfg["primitives"], reg["macros"], tasks),
             "supp_ops.tex": operations(cfg["operations"], reg, tasks),
             "supp_gallery.tex": gallery(cfg["gallery"], tasks, figdir)}
    for f, s in files.items():
        open(os.path.join(out, f), "w").write(s)
        print("wrote", os.path.join(cfg["out_dir"], f))
    os.makedirs(os.path.join(figdir, "annotation"), exist_ok=True)
    for p in glob.glob(os.path.join(ROOT, cfg["gallery"]["annotation"], "*.png")):
        shutil.copy(p, os.path.join(figdir, "annotation", os.path.basename(p)))


if __name__ == "__main__":
    main()
