"""Database schema for design-creative.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "projects": {
        "table_name": "design_creative_projects",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("owner_id", "INTEGER NOT NULL DEFAULT 0"),
            ("template_id", "INTEGER NOT NULL DEFAULT 0"),
            ("dimensions", "TEXT NOT NULL DEFAULT ''"),
            ("created_date", "TEXT NOT NULL DEFAULT ''"),
            ("modified_date", "TEXT NOT NULL DEFAULT ''"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
            ("elements", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "owner_id",
            "status",
        ],
    },
    "templates": {
        "table_name": "design_creative_templates",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("dimensions", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("tags", "TEXT NOT NULL DEFAULT ''"),
            ("use_count", "INTEGER NOT NULL DEFAULT 0"),
            ("preview_placeholder", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "category",
        ],
    },
    "assets": {
        "table_name": "design_creative_assets",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("type", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("tags", "TEXT NOT NULL DEFAULT ''"),
            ("svg", "TEXT NOT NULL DEFAULT ''"),
            ("src", "TEXT NOT NULL DEFAULT ''"),
            ("width", "INTEGER NOT NULL DEFAULT 200"),
            ("height", "INTEGER NOT NULL DEFAULT 200"),
        ],
        "indexes": [
            "type",
            "category",
        ],
    },
    "users": {
        "table_name": "design_creative_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("plan", "TEXT NOT NULL DEFAULT ''"),
            ("projects", "TEXT NOT NULL DEFAULT ''"),
            ("favorites", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "root_user_id",
        ],
    },
}
