"""Review round 1 (2026-10-05): the supplement section "Additional results and details" generated from
round1_numbers.json and compute_budget.json (no hand-copied numbers).

    python docs/figures/review/make_round1_supp.py [--out docs/paper/MiniWeb/sections/supp/supp_results.tex]
"""
import argparse, json, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
N = json.load(open(os.path.join(HERE, "round1_numbers.json")))
B = json.load(open(os.path.join(HERE, "compute_budget.json")))

ARM = {"base": "Single agent, untrained", "pooled": "Single agent, trained", "planner": "Planner, untrained executor",
       "planner_pooled": r"\miniwebagent{} (planner + trained executor)", "insta": "Planner + InSTA executor (26.4K steps)",
       "agent": "Planner + family specialists", "pooled7k": "Planner + 7K-trajectory executor (56.4K steps)",
       "base9b": "Qwen3.5-9B single agent, untrained", "planner9b": "Qwen3.5-9B planner, untrained executor",
       "fara": "Fara1.5-4B weights in our harness"}
FAMS = [("Navigation", "Nav."), ("Text entry", "Text"), ("Discrete selection", "Select"), ("Form transaction", "Form"),
        ("Out-of-page I/O", "I/O"), ("Drag & gesture", "Drag"), ("Reasoning base", "Reason")]


def pfmt(p):
    if p < 1e-3:
        e = 0
        while p < 10 ** -(e + 1):
            e += 1
        return f"$<10^{{-{e}}}$"
    return f"{p:.3f}" if p < 0.1 else f"{p:.2f}"       # the main text quotes the same three decimals


def holm(ps):
    order = sorted(range(len(ps)), key=lambda i: ps[i])
    adj, run = [0.0] * len(ps), 0.0
    for k, i in enumerate(order):
        run = max(run, min(1.0, (len(ps) - k) * ps[i]))
        adj[i] = run
    return adj


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "docs", "paper", "MiniWeb", "sections", "supp", "supp_results.tex"))
    out = ap.parse_args().out
    C, L = N["canonical"], []
    L += [r"% generated by docs/figures/review/make_round1_supp.py from round1_numbers.json; do not edit by hand",
          r"\section{Additional results and details}\label{app:results}",
          r"This section collects every configuration we ran, the tests behind the paper's comparisons, and the details "
          r"the main text summarizes. \miniweb{} and WebArena-Lite numbers are means over three runs (task verifiers and the "
          r"official evaluators); the live-web sets are one run on the normalized sets of App.~\ref{app:liveweb}. Evaluation "
          r"decodes greedily (temperature 0).", ""]

    # ── all configurations
    L += [r"\paragraph{All configurations.} Tab.~\ref{tab:supp-all} lists every configuration of Qwen3.5-4B we evaluated, "
          r"and the larger or web-trained models we could evaluate on the held-out tasks. The family specialists "
          r"(App.~\ref{app:specialists}) do not improve on the single pooled executor: they trail it on the held-out tasks, "
          r"WebArena-Lite, and Online-Mind2Web, and lead on WebVoyager without a significant difference "
          r"(Tab.~\ref{tab:supp-tests}). The 7K-trajectory executor matches the 3.1K one on the held-out tasks.", "",
          r"\begin{table}[h]", r"\centering", r"\small", r"\setlength{\tabcolsep}{4pt}",
          r"\begin{tabular}{@{}lccccc@{}}", r"\toprule",
          r" & Single & Held-out & WebArena- & Web- & Online- \\",
          r"Qwen3.5-4B configuration & primitives & tasks & Lite & Voyager & Mind2Web \\", r"\midrule"]

    def cell(arm, b, kind="mean"):
        x = C.get(arm, {}).get(b)
        if not x:
            return "--"
        if b in ("wv", "om2w"):
            return f"{x['seed1']:.1f}"
        return f"{x['mean']:.1f} $\\pm$ {x['se'] or 0:.1f}" if len(x["runs"]) > 1 else f"{x['mean']:.1f}"
    for arm in ("base", "pooled", "planner", "planner_pooled", "insta", "agent", "pooled7k"):
        L.append(f"{ARM[arm]} & " + " & ".join(cell(arm, b) for b in ("single", "heldout", "wa", "wv", "om2w")) + r" \\")
    L.append(r"\midrule")
    L.append(r"\multicolumn{6}{@{}l}{\textit{Other models on the 63 held-out tasks}} \\")
    for arm in ("base9b", "planner9b", "fara"):
        L.append(f"{ARM[arm]} & " + " & ".join(cell(arm, b) for b in ("single", "heldout")) + r" & -- & -- & -- \\")
    o = N["heldout_other_agents"]
    L.append(f"Fara1.5-4B, its own agent loop (one run) & -- & {o['Fara1.5-4B own loop']['verifier']:.1f} & -- & -- & -- \\\\")
    L += [r"\bottomrule", r"\end{tabular}",
          r"\caption{Task success (\%) of every configuration. Means $\pm$ standard error over runs where there are several "
          r"(three for \miniweb{} and WebArena-Lite, two for the Qwen3.5-9B single agent, whose two greedy runs score the "
          r"same). The main text's figures use the first five rows.}", r"\label{tab:supp-all}", r"\end{table}", ""]

    # ── tests
    groups = {}
    for t in N["tests"]:
        if t["mode"] != "main":
            continue
        groups.setdefault(t["label"].split(":")[0], []).append(t)
    L += [r"\paragraph{Tests.} Tab.~\ref{tab:supp-tests} lists every comparison the paper makes, with Holm's correction "
          r"within each question (the four or five benchmarks of one comparison). The figures' stars use the uncorrected $p$. "
          r"On WebArena-Lite, the first of the three runs alone gives larger gaps: the trained executor adds 10.4 points over "
          r"the untrained planner and our executor leads InSTA's by 7.8.", "",
          r"\begin{table}[h]", r"\centering", r"\small", r"\setlength{\tabcolsep}{4pt}",
          r"\begin{tabular}{@{}llcccc@{}}", r"\toprule", r"Question & Benchmark & A $\rightarrow$ B & $\Delta$ & $p$ & Holm $p$ \\",
          r"\midrule"]
    names = {"practice": "Practice alone (single agent)", "planning": "Planning alone (untrained executor)",
             "trained executor": "Trained executor (over the planner)", "MiniWebAgent vs single": r"\miniwebagent{} vs.\ single agent",
             "InSTA executor": "InSTA executor (over the planner)", "ours vs InSTA": "Our executor vs.\ InSTA's",
             "specialists vs pooled": "Specialists vs.\ pooled executor", "7K vs 3.1K executor": "7K vs.\ 3.1K executor",
             "MiniWebAgent vs trained single": r"\miniwebagent{} vs.\ trained single agent"}
    bn = {"single": "Single primitives", "heldout": "Held-out tasks", "wa": "WebArena-Lite", "wv": "WebVoyager", "om2w": "Online-Mind2Web"}
    for g, ts in groups.items():
        adj = holm([t["p"] for t in ts])
        for k, (t, q) in enumerate(zip(ts, adj)):
            L.append(f"{names.get(g, g) if k == 0 else ''} & {bn[t['bench']]} & {t['A']:.1f} $\\rightarrow$ {t['B']:.1f} & "
                     f"{t['diff']:+.1f} & {pfmt(t['p'])} & {pfmt(q)} \\\\")
        L.append(r"\addlinespace[2pt]")
    L += [r"\bottomrule", r"\end{tabular}",
          r"\caption{Every comparison of the paper. Paired permutation test over tasks on \miniweb{} and WebArena-Lite "
          r"(per-task means over three runs); exact McNemar test on the live web. Holm $p$: corrected within each question.}",
          r"\label{tab:supp-tests}", r"\end{table}", ""]

    # ── primitives inside the held-out tasks
    F = N["family_inside_heldout"]
    L += [r"\paragraph{Primitives inside the human tasks.} The generated single-primitive tasks of Fig.~\ref{fig:rq2} share "
          r"\miniwebgen{}'s instruction style. Tab.~\ref{tab:supp-inside} measures practice on the human tasks instead: the "
          r"share of primitive instances passed inside the 63 held-out multi-step tasks. Trained alone, the agent passes as "
          r"many as before; with the planner, the trained executor passes more than the untrained one in every family. The "
          r"drag \& gesture column rests on four instances per run.", "",
          r"\begin{table}[h]", r"\centering", r"\small", r"\setlength{\tabcolsep}{4pt}",
          r"\begin{tabular}{@{}l" + "c" * (len(FAMS) + 1) + r"@{}}", r"\toprule",
          "Qwen3.5-4B & " + " & ".join(s for _, s in FAMS) + r" & All \\",
          " & " + " & ".join(f"\\scriptsize({F['base'][f][1]})" for f, _ in FAMS) + f" & \\scriptsize({F['base']['All'][1]}) \\\\",
          r"\midrule"]
    for arm in ("base", "pooled", "planner", "planner_pooled", "insta", "agent"):
        L.append(f"{ARM[arm]} & " + " & ".join(f"{F[arm][f][0]:.0f}" for f, _ in FAMS) + f" & {F[arm]['All'][0]:.1f} \\\\")
    L += [r"\bottomrule", r"\end{tabular}",
          r"\caption{Primitive instances passed (\%) inside the 63 held-out human tasks, by family (task verifiers, three runs; "
          r"instances per run in brackets). An instance after a failed one counts as failed if the agent never reached it.}",
          r"\label{tab:supp-inside}", r"\end{table}", ""]

    # ── why practice alone fails on tasks
    fm = N["failure_modes"]
    L += [r"\paragraph{Why practice alone does not raise task success.} Trained on episodes that end after one primitive, the "
          r"single agent ends whole tasks early: its median episode shrinks from "
          f"{fm['base/heldout']['median_steps']} to {fm['pooled/heldout']['median_steps']} steps on the held-out tasks, from "
          f"{fm['base/wa']['median_steps']} to {fm['pooled/wa']['median_steps']} on WebArena-Lite, from "
          f"{fm['base/wv']['median_steps']} to {fm['pooled/wv']['median_steps']} on WebVoyager, and from "
          f"{fm['base/om2w']['median_steps']} to {fm['pooled/om2w']['median_steps']} on Online-Mind2Web, while the untrained "
          f"agent reaches its action budget in {fm['base/wa']['at_cap_40_pct']:.0f}\\% of WebArena-Lite episodes. The trained "
          r"agent's WebVoyager run used a 40-action budget instead of 100; "
          f"{fm['pooled/wv']['at_cap_40_pct']:.0f}\\% of its episodes reached it, so its WebVoyager number may be "
          r"slightly low, but its median episode (9 steps) is far below either budget.", ""]

    # ── WebArena-Lite per site
    W = N["wa_domains"]
    sites = [("gitlab", "GitLab"), ("reddit", "Reddit"), ("shopping", "Shopping"), ("shopping_admin", "Shopping admin"),
             ("map", "Map"), ("no reddit/gitlab", "Without Reddit, GitLab"), ("ALL", "All")]
    nr = {x["a"] + "/" + x["mode"]: x for x in N["wa_no_reddit_gitlab"]}
    L += [r"\paragraph{WebArena-Lite by site.} Two training sites reuse WebArena's Reddit and GitLab data "
          r"(Tab.~\ref{tab:supp-licenses}). Tab.~\ref{tab:supp-wa} splits WebArena-Lite by site. Without the Reddit and "
          f"GitLab tasks, \\miniwebagent{{}} still gains {nr['base/3run']['diff']:.1f} points over the untrained single agent "
          f"($p={nr['base/3run']['p']:.3f}$) and {nr['planner/3run']['diff']:.1f} over the untrained planner "
          f"($p={nr['planner/3run']['p']:.2f}$). Over the single agent the largest gain is on Reddit; over the untrained planner, "
          f"the trained executor gains most on GitLab and loses on Reddit.", "",
          r"\begin{table}[h]", r"\centering", r"\small", r"\setlength{\tabcolsep}{4pt}",
          r"\begin{tabular}{@{}lcccccc@{}}", r"\toprule",
          r"Site & Tasks & Single, untr. & Single, trained & Planner, untr. & \miniwebagent{} & InSTA exec. \\", r"\midrule"]
    for key, name in sites:
        n = W["base/3run"].get(key, ("-", 0))[1]
        L.append(f"{name} & {n} & " + " & ".join(f"{W[a + '/3run'][key][0]:.1f}"
                                                   for a in ("base", "pooled", "planner", "planner_pooled", "insta")) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}", r"\caption{WebArena-Lite success (\%) by site, mean of three runs (official evaluators).}",
          r"\label{tab:supp-wa}", r"\end{table}", ""]

    # ── compute per episode
    L += [r"\paragraph{Model calls.} Planner turns do not count toward the site-action budget, so \miniwebagent{} makes more "
          r"model calls than the single agent (Tab.~\ref{tab:supp-calls}). Its planner reaches its turn cap (25 on \miniweb{} "
          f"and WebArena-Lite, 60 on the live web) in {N['planner_caps']['heldout']['at_turn_cap_pct']:.0f}\\%, "
          f"{N['planner_caps']['wa']['at_turn_cap_pct']:.0f}\\%, {N['planner_caps']['wv']['at_turn_cap_pct']:.0f}\\%, and "
          f"{N['planner_caps']['om2w']['at_turn_cap_pct']:.0f}\\% of the episodes on the four benchmarks.", "",
          r"\begin{table}[h]", r"\centering", r"\small", r"\setlength{\tabcolsep}{4pt}",
          r"\begin{tabular}{@{}lcccc@{}}", r"\toprule", r"Model calls per episode (mean) & Held-out & WebArena-Lite & WebVoyager & Online-Mind2Web \\",
          r"\midrule"]
    for arm, name in (("single, untrained", "Single agent, untrained"), ("single, trained", "Single agent, trained"),
                      ("planner, untrained", "Planner, untrained executor"), ("MiniWebAgent", r"\miniwebagent{}")):
        L.append(f"{name} & " + " & ".join(f"{B[arm][b]['calls']['mean']:.1f}" for b in ("miniweb", "wa", "wv", "om2w")) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}",
          r"\caption{Model calls per episode: agent steps of the single agent; planner turns plus executor steps of the planner "
          r"agents. The action budget is the same for all (40 site actions on \miniweb{} and WebArena-Lite, 100 on the live web).}",
          r"\label{tab:supp-calls}", r"\end{table}", ""]

    # ── diagnosis robustness and data details
    dm = N["drag_modality"]
    L += [r"\paragraph{Robustness of the skill profiles.} Counting only the primitive instances whose earlier primitives in "
          r"the task all passed, so that a family is not penalized for failures upstream of it, drag \& gesture remains the "
          r"weakest family for each of the ten agents. Averaged over the agents, success by chain length stays within "
          f"{N['pn']['max_abs_dev']:.1f} points of the independent-primitive prediction $p^n$ at every length "
          r"(Fig.~\ref{fig:chain}, left). Among the six agents with their own loops, five have a drag action in their released "
          r"action spaces (Fara1.5-4B: \texttt{left\_click\_drag}; MolmoWeb: \texttt{drag\_and\_drop}; UI-TARS-1.5-7B: "
          r"\texttt{drag}; OpenCUA-7B: \texttt{dragTo}) and still pass at most 17\% of drag instances; Fara-7B's has none, so "
          r"its 0\% is by construction.", "",
          r"\paragraph{The drag \& gesture training data.} Of the drag \& gesture trajectories in the training set, "
          f"{dm['sign_by_freeformdrawing'].get('drag/draw', 0)} draw signatures, "
          f"{dm['reposition_by_drag'].get('drag/draw', 0)} reposition items, and "
          f"{dm['search_by_pan_zoom'].get('drag/draw', 0)} pan a map, all with real drags; the "
          f"{sum(v for k, v in dm['filter_by_slider'].items() if not k.startswith('_'))} slider trajectories set the value by "
          r"clicking on the track, which the sliders accept, and the playback and ranking trajectories use clicks.", "",
          r"\paragraph{Training details.} The executor is a rank-64 LoRA ($\alpha=128$, dropout 0.05) on the language model's "
          r"attention and MLP projections, trained for one epoch on the 27,646 steps of $\mathcal{D}$ (3,128 plain trajectories, "
          r"857 two-trajectory chains, and 629 trajectories with an injected and corrected mistake), at learning rate "
          r"$10^{-4}$ with a cosine schedule and a batch of 8 steps. The InSTA executor uses the same recipe on 26,368 steps "
          r"from 3,691 trajectories of InSTA's released SFT set: its text-only steps are mapped to our prompt template and "
          r"action schema (click, input, select, scroll, navigate, back, done), and carry no screenshot.", "",
          r"\paragraph{Held-out sites.} The 13 held-out sites were fixed once, before any trajectory was generated. Three of "
          r"the 63 held-out tasks also use a training site (email, team chat, or the code editor) for a cross-site step.", ""]
    open(out, "w").write("\n".join(L) + "\n")
    print("wrote", out)


if __name__ == "__main__":
    main()
