"""Database schema for conference-review-submission.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "venues": {
        "table_name": "conference_review_submission_venues",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("full_name", "TEXT NOT NULL DEFAULT ''"),
            ("year", "INTEGER NOT NULL DEFAULT 0"),
            ("type", "TEXT NOT NULL DEFAULT ''"),
            ("location", "TEXT NOT NULL DEFAULT ''"),
            ("dates", "TEXT NOT NULL DEFAULT ''"),
            ("website", "TEXT NOT NULL DEFAULT ''"),
            ("submission_deadline", "TEXT NOT NULL DEFAULT ''"),
            ("notification_date", "TEXT NOT NULL DEFAULT ''"),
            ("review_visibility", "TEXT NOT NULL DEFAULT 'public'"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "year",
            "status",
        ],
    },
    "papers": {
        "table_name": "conference_review_submission_papers",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("authors", "TEXT NOT NULL DEFAULT ''"),
            ("abstract", "TEXT NOT NULL DEFAULT ''"),
            ("conference", "TEXT NOT NULL DEFAULT ''"),
            ("venue_id", "TEXT NOT NULL DEFAULT ''"),
            ("accepted", "INTEGER NOT NULL DEFAULT 0"),
            ("reviews", "TEXT NOT NULL DEFAULT ''"),
            ("histories", "TEXT NOT NULL DEFAULT ''"),
            ("_source_file", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "venue_id",
        ],
    },
    "users": {
        "table_name": "conference_review_submission_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("role", "TEXT NOT NULL DEFAULT ''"),
            ("expertise", "TEXT NOT NULL DEFAULT ''"),
            ("assigned_papers", "TEXT NOT NULL DEFAULT ''"),
            ("bids", "TEXT NOT NULL DEFAULT ''"),
            ("venue_roles", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "role",
            "root_user_id",
        ],
    },
}
