"""Database schema for code-editor-execution.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "snippets": {
        "table_name": "code_editor_execution_snippets",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("language", "TEXT NOT NULL DEFAULT ''"),
            ("code", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("difficulty", "TEXT NOT NULL DEFAULT ''"),
            ("expected_output", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "category",
        ],
    },
    "users": {
        "table_name": "code_editor_execution_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("saved_snippets", "TEXT NOT NULL DEFAULT ''"),
            ("execution_history", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "root_user_id",
        ],
    },
}
