"""Database schema for video.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "comments": {
        "table_name": "video_comments",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("video_id", "INTEGER NOT NULL DEFAULT 0"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("display_name", "TEXT NOT NULL DEFAULT ''"),
            ("text", "TEXT NOT NULL DEFAULT ''"),
            ("timestamp", "TEXT NOT NULL DEFAULT ''"),
            ("likes", "INTEGER NOT NULL DEFAULT 0"),
            ("parent_comment_id", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "timestamp",
            "user_id",
        ],
    },
    "playlists": {
        "table_name": "video_playlists",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("visibility", "TEXT NOT NULL DEFAULT ''"),
            ("created_date", "TEXT NOT NULL DEFAULT ''"),
            ("updated_date", "TEXT NOT NULL DEFAULT ''"),
            ("items", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "user_id",
        ],
    },
    "users": {
        "table_name": "video_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("display_name", "TEXT NOT NULL DEFAULT ''"),
            ("channel_name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("avatar_url", "TEXT NOT NULL DEFAULT ''"),
            ("subscriber_count", "INTEGER NOT NULL DEFAULT 0"),
            ("videos_count", "INTEGER NOT NULL DEFAULT 0"),
            ("joined_date", "TEXT NOT NULL DEFAULT ''"),
            ("about", "TEXT NOT NULL DEFAULT ''"),
            ("links", "TEXT NOT NULL DEFAULT ''"),
            ("is_verified", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "root_user_id",
        ],
    },
    "videos": {
        "table_name": "video_videos",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("channel_id", "INTEGER NOT NULL DEFAULT 0"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("duration_seconds", "INTEGER NOT NULL DEFAULT 0"),
            ("views", "INTEGER NOT NULL DEFAULT 0"),
            ("likes", "INTEGER NOT NULL DEFAULT 0"),
            ("dislikes", "INTEGER NOT NULL DEFAULT 0"),
            ("upload_date", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("tags", "TEXT NOT NULL DEFAULT ''"),
            ("thumbnail_url", "TEXT NOT NULL DEFAULT ''"),
            ("video_url", "TEXT NOT NULL DEFAULT ''"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "category",
            "status",
            "user_id",
        ],
    },
    "watch_history": {
        "table_name": "video_watch_history",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("video_id", "INTEGER NOT NULL DEFAULT 0"),
            ("video_title", "TEXT NOT NULL DEFAULT ''"),
            ("channel_name", "TEXT NOT NULL DEFAULT ''"),
            ("watched_at", "TEXT NOT NULL DEFAULT ''"),
            ("progress_percent", "INTEGER NOT NULL DEFAULT 0"),
            ("duration_seconds", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "user_id",
        ],
    },
}
