"""Database schema for health-fitness-tracking.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "daily_stats": {
        "table_name": "health_fitness_tracking_daily_stats",
        "columns": [
            ("row_id", "INTEGER PRIMARY KEY"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("steps", "INTEGER NOT NULL DEFAULT 0"),
            ("distance_km", "REAL NOT NULL DEFAULT 0.0"),
            ("calories_burned", "INTEGER NOT NULL DEFAULT 0"),
            ("active_minutes", "INTEGER NOT NULL DEFAULT 0"),
            ("floors_climbed", "INTEGER NOT NULL DEFAULT 0"),
            ("sleep_hours", "REAL NOT NULL DEFAULT 0.0"),
            ("sleep_quality", "TEXT NOT NULL DEFAULT ''"),
            ("water_ml", "INTEGER NOT NULL DEFAULT 0"),
            ("weight_kg", "REAL NOT NULL DEFAULT 0.0"),
        ],
        "indexes": [
            "date",
            "user_id",
        ],
    },
    "goals": {
        "table_name": "health_fitness_tracking_goals",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("goals", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "user_id",
        ],
    },
    "nutrition": {
        "table_name": "health_fitness_tracking_nutrition",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("meal_type", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("location", "TEXT NOT NULL DEFAULT ''"),
            ("calories", "INTEGER NOT NULL DEFAULT 0"),
            ("protein_g", "INTEGER NOT NULL DEFAULT 0"),
            ("carbs_g", "INTEGER NOT NULL DEFAULT 0"),
            ("fat_g", "INTEGER NOT NULL DEFAULT 0"),
            ("fiber_g", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "date",
            "user_id",
        ],
    },
    "users": {
        "table_name": "health_fitness_tracking_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("display_name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("date_of_birth", "TEXT NOT NULL DEFAULT ''"),
            ("gender", "TEXT NOT NULL DEFAULT ''"),
            ("height_cm", "INTEGER NOT NULL DEFAULT 0"),
            ("weight_kg", "REAL NOT NULL DEFAULT 0.0"),
            ("fitness_goals", "TEXT NOT NULL DEFAULT ''"),
            ("activity_level", "TEXT NOT NULL DEFAULT ''"),
            ("connected_devices", "TEXT NOT NULL DEFAULT ''"),
            ("joined_date", "TEXT NOT NULL DEFAULT ''"),
            ("premium_member", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "root_user_id",
        ],
    },
    "workouts": {
        "table_name": "health_fitness_tracking_workouts",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("type", "TEXT NOT NULL DEFAULT ''"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("start_time", "TEXT NOT NULL DEFAULT ''"),
            ("duration_minutes", "INTEGER NOT NULL DEFAULT 0"),
            ("calories_burned", "INTEGER NOT NULL DEFAULT 0"),
            ("heart_rate_avg", "INTEGER NOT NULL DEFAULT 0"),
            ("heart_rate_max", "INTEGER NOT NULL DEFAULT 0"),
            ("location", "TEXT NOT NULL DEFAULT ''"),
            ("notes", "TEXT NOT NULL DEFAULT ''"),
            ("exercises", "TEXT NOT NULL DEFAULT ''"),
            ("distance_km", "REAL NOT NULL DEFAULT 0.0"),
            ("elevation_gain_m", "INTEGER NOT NULL DEFAULT 0"),
            ("companions", "TEXT NOT NULL DEFAULT ''"),
            ("pace_min_per_km", "REAL NOT NULL DEFAULT 0.0"),
        ],
        "indexes": [
            "date",
            "type",
            "user_id",
        ],
    },
}
