"""Database schema for wikis.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "articles": {
        "table_name": "wikis_articles",
        "columns": [
            ("row_id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("path", "TEXT NOT NULL DEFAULT ''"),
            ("content", "TEXT NOT NULL DEFAULT ''"),
        ],
    },
    "categories": {
        "table_name": "wikis_categories",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("page_count", "INTEGER NOT NULL DEFAULT 0"),
        ],
    },
    "pages": {
        "table_name": "wikis_pages",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("slug", "TEXT NOT NULL DEFAULT ''"),
            ("content", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("author_id", "INTEGER NOT NULL DEFAULT 0"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("updated_at", "TEXT NOT NULL DEFAULT ''"),
            ("views", "INTEGER NOT NULL DEFAULT 0"),
            ("linked_pages", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "author_id",
            "category",
            "created_at",
            "updated_at",
        ],
    },
    "revisions": {
        "table_name": "wikis_revisions",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("page_id", "INTEGER NOT NULL DEFAULT 0"),
            ("editor_id", "INTEGER NOT NULL DEFAULT 0"),
            ("timestamp", "TEXT NOT NULL DEFAULT ''"),
            ("summary", "TEXT NOT NULL DEFAULT ''"),
            ("diff_lines_added", "INTEGER NOT NULL DEFAULT 0"),
            ("diff_lines_removed", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "timestamp",
        ],
    },
    "users": {
        "table_name": "wikis_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("display_name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("bio", "TEXT NOT NULL DEFAULT ''"),
            ("role", "TEXT NOT NULL DEFAULT ''"),
            ("joined", "TEXT NOT NULL DEFAULT ''"),
            ("edit_count", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "role",
        ],
    },
}
