"""Database schema for blogs.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "comments": {
        "table_name": "blogs_comments",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("post_id", "INTEGER NOT NULL DEFAULT 0"),
            ("author_username", "TEXT NOT NULL DEFAULT ''"),
            ("author_display_name", "TEXT NOT NULL DEFAULT ''"),
            ("body", "TEXT NOT NULL DEFAULT ''"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "date",
            "post_id",
        ],
    },
    "posts": {
        "table_name": "blogs_posts",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("body", "TEXT NOT NULL DEFAULT ''"),
            ("author_id", "INTEGER NOT NULL DEFAULT 0"),
            ("author_username", "TEXT NOT NULL DEFAULT ''"),
            ("author_display_name", "TEXT NOT NULL DEFAULT ''"),
            ("author_avatar", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("tags", "TEXT NOT NULL DEFAULT ''"),
            ("image_url", "TEXT NOT NULL DEFAULT ''"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("notes_count", "INTEGER NOT NULL DEFAULT 0"),
            ("is_pinned", "INTEGER NOT NULL DEFAULT 0"),
            ("shared_count", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "author_id",
            "category",
            "date",
        ],
    },
    "reports": {
        "table_name": "blogs_reports",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("post_id", "INTEGER NOT NULL DEFAULT 0"),
            ("reporter_username", "TEXT NOT NULL DEFAULT ''"),
            ("reporter_display_name", "TEXT NOT NULL DEFAULT ''"),
            ("reason", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("date_reported", "TEXT NOT NULL DEFAULT ''"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "post_id",
            "status",
        ],
    },
    "users": {
        "table_name": "blogs_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("display_name", "TEXT NOT NULL DEFAULT ''"),
            ("bio", "TEXT NOT NULL DEFAULT ''"),
            ("avatar", "TEXT NOT NULL DEFAULT ''"),
            ("followed_blogs", "TEXT NOT NULL DEFAULT ''"),
            ("saved_posts", "TEXT NOT NULL DEFAULT ''"),
            ("subscribed_tags", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "root_user_id",
        ],
    },
}
