"""Database schema for petitions-voting-info.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "elections": {
        "table_name": "petitions_voting_info_elections",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("type", "TEXT NOT NULL DEFAULT ''"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
            ("jurisdiction", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("races", "TEXT NOT NULL DEFAULT ''"),
            ("ballot_measures", "TEXT NOT NULL DEFAULT ''"),
            ("turnout", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "date",
            "status",
            "type",
        ],
    },
    "petitions": {
        "table_name": "petitions_voting_info_petitions",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("creator_id", "INTEGER NOT NULL DEFAULT 0"),
            ("creator_name", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("signatures_required", "INTEGER NOT NULL DEFAULT 0"),
            ("signatures_current", "INTEGER NOT NULL DEFAULT 0"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("deadline", "TEXT NOT NULL DEFAULT ''"),
            ("tags", "TEXT NOT NULL DEFAULT ''"),
            ("related_links", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "category",
            "created_at",
            "creator_id",
            "status",
        ],
    },
    "signatures": {
        "table_name": "petitions_voting_info_signatures",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("petition_id", "INTEGER NOT NULL DEFAULT 0"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("user_name", "TEXT NOT NULL DEFAULT ''"),
            ("signed_at", "TEXT NOT NULL DEFAULT ''"),
            ("comment", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "user_id",
        ],
    },
    "users": {
        "table_name": "petitions_voting_info_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("display_name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("voter_registration_status", "TEXT NOT NULL DEFAULT ''"),
            ("registered_address", "TEXT NOT NULL DEFAULT ''"),
            ("precinct", "TEXT NOT NULL DEFAULT ''"),
            ("party_affiliation", "TEXT NOT NULL DEFAULT ''"),
            ("registration_date", "TEXT NOT NULL DEFAULT ''"),
            ("profile", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "root_user_id",
        ],
    },
    "voter_info": {
        "table_name": "petitions_voting_info_voter_info",
        "columns": [
            ("row_id", "INTEGER PRIMARY KEY"),
            ("jurisdiction", "TEXT NOT NULL DEFAULT ''"),
            ("election_authority", "TEXT NOT NULL DEFAULT ''"),
            ("polling_locations", "TEXT NOT NULL DEFAULT ''"),
            ("registration_info", "TEXT NOT NULL DEFAULT ''"),
            ("voting_methods", "TEXT NOT NULL DEFAULT ''"),
            ("upcoming_deadlines", "TEXT NOT NULL DEFAULT ''"),
            ("ballot_measure_explanations", "TEXT NOT NULL DEFAULT ''"),
        ],
    },
}
