"""Database schema for email.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "emails": {
        "table_name": "email_emails",
        "columns": [
            ("from_", "TEXT NOT NULL DEFAULT ''"),
            ("to", "TEXT NOT NULL DEFAULT ''"),
            ("cc", "TEXT NOT NULL DEFAULT ''"),
            ("subject", "TEXT NOT NULL DEFAULT ''"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("body", "TEXT NOT NULL DEFAULT ''"),
            ("message_id", "TEXT PRIMARY KEY"),
            ("path", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "date",
        ],
    },
    "sent_messages": {
        "table_name": "email_sent_messages",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("from_", "TEXT NOT NULL DEFAULT ''"),
            ("to", "TEXT NOT NULL DEFAULT ''"),
            ("cc", "TEXT NOT NULL DEFAULT ''"),
            ("subject", "TEXT NOT NULL DEFAULT ''"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("body", "TEXT NOT NULL DEFAULT ''"),
            ("message_id", "TEXT NOT NULL DEFAULT ''"),
            ("folder", "TEXT NOT NULL DEFAULT ''"),
            ("labels", "TEXT NOT NULL DEFAULT ''"),
            ("is_read", "INTEGER NOT NULL DEFAULT 0"),
            ("is_starred", "INTEGER NOT NULL DEFAULT 0"),
            ("has_attachment", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "date",
            "folder",
        ],
    },
    "users": {
        "table_name": "email_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("email_address", "TEXT NOT NULL DEFAULT ''"),
            ("folders", "TEXT NOT NULL DEFAULT ''"),
            ("labels", "TEXT NOT NULL DEFAULT ''"),
            ("signature", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "root_user_id",
        ],
    },
}
