"""Database schema for real-estate-buy-rent.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "agents": {
        "table_name": "real_estate_buy_rent_agents",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("phone", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("agency", "TEXT NOT NULL DEFAULT ''"),
            ("listings_count", "INTEGER NOT NULL DEFAULT 0"),
            ("rating", "REAL NOT NULL DEFAULT 0.0"),
        ],
    },
    "inquiries": {
        "table_name": "real_estate_buy_rent_inquiries",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("listing_id", "INTEGER NOT NULL DEFAULT 0"),
            ("message", "TEXT NOT NULL DEFAULT ''"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "date",
            "listing_id",
            "status",
            "user_id",
        ],
    },
    "listings": {
        "table_name": "real_estate_buy_rent_listings",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("address", "TEXT NOT NULL DEFAULT ''"),
            ("city", "TEXT NOT NULL DEFAULT ''"),
            ("state", "TEXT NOT NULL DEFAULT ''"),
            ("zip", "TEXT NOT NULL DEFAULT ''"),
            ("type", "TEXT NOT NULL DEFAULT ''"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
            ("price", "INTEGER NOT NULL DEFAULT 0"),
            ("rent_monthly", "INTEGER NOT NULL DEFAULT 0"),
            ("bedrooms", "INTEGER NOT NULL DEFAULT 0"),
            ("bathrooms", "REAL NOT NULL DEFAULT 0.0"),
            ("sqft", "INTEGER NOT NULL DEFAULT 0"),
            ("lot_sqft", "INTEGER NOT NULL DEFAULT 0"),
            ("year_built", "INTEGER NOT NULL DEFAULT 0"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("features", "TEXT NOT NULL DEFAULT ''"),
            ("agent_id", "INTEGER NOT NULL DEFAULT 0"),
            ("listed_date", "TEXT NOT NULL DEFAULT ''"),
            ("photos_count", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "state",
            "status",
            "type",
        ],
    },
    "listings_raw": {
        "table_name": "real_estate_buy_rent_listings_raw",
        "columns": [
            ("row_id", "INTEGER PRIMARY KEY"),
            ("brokered_by", "REAL NOT NULL DEFAULT 0.0"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
            ("price", "REAL NOT NULL DEFAULT 0.0"),
            ("bed", "INTEGER NOT NULL DEFAULT 0"),
            ("bath", "INTEGER NOT NULL DEFAULT 0"),
            ("acre_lot", "REAL NOT NULL DEFAULT 0.0"),
            ("street", "REAL NOT NULL DEFAULT 0.0"),
            ("city", "TEXT NOT NULL DEFAULT ''"),
            ("state", "TEXT NOT NULL DEFAULT ''"),
            ("zip_code", "INTEGER NOT NULL DEFAULT 0"),
            ("house_size", "REAL NOT NULL DEFAULT 0.0"),
            ("prev_sold_date", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "state",
            "status",
        ],
    },
    "saved": {
        "table_name": "real_estate_buy_rent_saved",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("listing_id", "INTEGER NOT NULL DEFAULT 0"),
            ("saved_date", "TEXT NOT NULL DEFAULT ''"),
            ("notes", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "listing_id",
            "user_id",
        ],
    },
    "users": {
        "table_name": "real_estate_buy_rent_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("phone", "TEXT NOT NULL DEFAULT ''"),
            ("role", "TEXT NOT NULL DEFAULT ''"),
            ("bio", "TEXT NOT NULL DEFAULT ''"),
            ("member_since", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "role",
        ],
    },
}
