"""Write the paper's result tables (LaTeX fragments) from tables_config.yaml and the run directories.

Each run cell prints the mean over seeds, with the standard deviation when there are several seeds (unless the table
sets std: false) and a superscript seed count when there are fewer than three. Fixed `values` print as given. A row
with compare_to: <named runs> gets a second line of p-values against those runs, from the same tests as
paper_stats.py (paired permutation over tasks after averaging seeds; exact McNemar for single live-web runs).

    python docs/figures/tables/make_tables.py [--config docs/figures/tables/tables_config.yaml]
"""
import argparse, os, statistics as st, sys
import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "common"))
from results import ROOT, task_rates, primitive_filter  # noqa: E402
sys.path.insert(0, HERE)
from paper_stats import per_task, permutation, mcnemar  # noqa: E402


def rates(bench, runs):
    return task_rates(bench["kind"], runs, bench.get("tasks"), only=primitive_filter(bench.get("primitives"))) if runs else []


def cell(bench, runs, bold, todo, std=True):
    if todo:
        return "\\todo{run}"
    if not runs:
        return "--"
    xs = rates(bench, runs)
    m = f"{st.mean(xs):.1f}"
    m = f"\\textbf{{{m}}}" if bold else m
    sd = f"\\std{{{st.stdev(xs):.1f}}}" if std and len(xs) > 1 else ""
    sup = f"$^{len(xs)}$" if 0 < len(xs) < 3 and bench["kind"] in ("miniweb", "webarena") else ""
    return m + sd + sup


def pvalue(bench, ra, rb):
    """p of runs rb against runs ra, as in paper_stats.py; printed like .013, .22, <.001."""
    if not ra or not rb:
        return ""
    pa, pb = per_task(bench, ra), per_task(bench, rb)
    if len(ra) == 1 and len(rb) == 1 and bench["kind"] in ("webvoyager", "om2w"):
        p = mcnemar(pa, pb)[3]
    else:
        p = permutation(pa, pb)[3]
    return "$<$.001" if p < 0.001 else ("1.0" if p >= 0.995 else f"{p:.2g}".lstrip("0"))


def judge_rate(path, ids):
    """Task success by the task verifiers over `ids`, from an RQ1 run's judge.jsonl (one run, all 376 tasks)."""
    import json
    rs = [json.loads(l) for l in open(os.path.join(ROOT, path)) if l.strip()]
    rs = [r for r in rs if r["task_id"] in ids]
    return 100 * sum(bool(r.get("verifier")) for r in rs) / len(rs) if rs else None


def table(t, cfg):
    cols, benches, named = t["columns"], cfg["benchmarks"], cfg["runs"]
    ex, std = bool(t.get("extra_column")), t.get("std", True)
    from results import task_outcomes
    held_ids = set(task_outcomes("miniweb", named[t.get("heldout_ids_from", "base")]["heldout"][0]))
    def measured(r, c):                                  # the row's own mean for column c, or None
        runs = named.get(r["runs"], {}) if isinstance(r.get("runs"), str) else (r.get("runs") or {})
        if c == "heldout" and r.get("judge"):
            return judge_rate(r["judge"], held_ids)
        xs = rates(benches[c], runs.get(c) or []) if runs.get(c) else []
        return st.mean(xs) if xs else None
    head = lambda h: "\\begin{tabular}[c]{@{}c@{}}" + h + "\\end{tabular}"
    lines = ["% generated by docs/figures/tables/make_tables.py from tables_config.yaml; do not edit by hand",
             "\\providecommand{\\std}[1]{{\\scriptsize$\\pm$#1}}",
             "\\begin{table*}[t]" if t.get("wide") else "\\begin{table}[t]", "\\centering", "\\footnotesize",
             "\\setlength{\\tabcolsep}{3.5pt}",
             "\\resizebox{\\textwidth}{!}{%" if t.get("wide") else "\\resizebox{\\linewidth}{!}{%",   # always fits
             "\\begin{tabular}{@{}l" + "c" * (len(cols) + (1 if ex else 0)) + "@{}}", "\\toprule",
             *group_header(t, len(cols), ex),
             (" & " + head(t["extra_column"]["head"]) if ex else "") + " & " + " & ".join(head(benches[c]["head"]) for c in cols) + " \\\\",
             "\\midrule"]
    best = {}                                            # bold_best: the highest measured value of each column
    if t.get("bold_best"):                               # (reported numbers from other papers are never bold)
        for c in cols:
            ms = [m for g in t["groups"] for r in g["rows"] for m in [measured(r, c)] if m is not None]
            best[c] = max(ms) if ms else None
    for gi, g in enumerate(t["groups"]):
        if gi:
            lines.append("\\midrule")
        lines.append(f"\\multicolumn{{{len(cols) + 1 + ex}}}{{@{{}}l}}{{\\textit{{{g['name']}}}}} \\\\")
        for r in g["rows"]:
            runs = named.get(r["runs"], {}) if isinstance(r.get("runs"), str) else (r.get("runs") or {})
            vals = []
            for c in cols:
                m = measured(r, c)
                if c == "heldout" and r.get("judge") and m is not None:      # one RQ1 run, its task verifiers
                    v = f"{m:.1f}"
                    vals.append(f"\\textbf{{{v}}}" if best.get(c) is not None and abs(m - best[c]) < 1e-9 else v)
                elif c in (r.get("values") or {}):                           # reported elsewhere: printed as given
                    v = r["values"][c]
                    vals.append("--" if v is None else (v if isinstance(v, str) else f"{v:.1f}"))
                elif runs.get(c):
                    bold = r.get("bold") or (best.get(c) is not None and m is not None and abs(m - best[c]) < 1e-9)
                    vals.append(cell(benches[c], runs.get(c) or [], bold, c in (r.get("todo") or []), std))
                else:
                    vals.append("--")
            lines.append(f"{r['label']}" + (f" & {r.get('extra', '')}" if ex else "") + " & " + " & ".join(vals) + " \\\\")
            if r.get("compare_to"):                      # a line of p-values under the row
                ref = named.get(r["compare_to"], {})
                ps = [pvalue(benches[c], ref.get(c) or [], runs.get(c) or []) for c in cols]
                lines.append(("" if not ex else " &") + " & " + " & ".join(f"{{\\scriptsize ({x})}}" if x else "" for x in ps) + " \\\\[1pt]")
    lines += ["\\bottomrule", "\\end{tabular}}", f"\\caption{{{t['caption']}}}", f"\\label{{{t['label']}}}",
              "\\end{table*}" if t.get("wide") else "\\end{table}", ""]
    return "\n".join(lines)


def group_header(t, ncols, ex=True):
    """Optional spanning headers over the benchmark columns: column_groups: [{label, span}, ...]."""
    gs = t.get("column_groups")
    if not gs:
        return []
    cells, rules, col = [], [], 3 if ex else 2           # column 1 is the arm, then the optional extra column
    for g in gs:
        cells.append(f"\\multicolumn{{{g['span']}}}{{c}}{{{g['label']}}}")
        rules.append(f"\\cmidrule(lr){{{col}-{col + g['span'] - 1}}}")
        col += g["span"]
    return [(" & & " if ex else " & ") + " & ".join(cells) + " \\\\", "".join(rules)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=os.path.join(HERE, "tables_config.yaml"))
    cfg = yaml.safe_load(open(ap.parse_args().config))
    for t in cfg["tables"]:
        out = os.path.join(ROOT, t["out"])
        os.makedirs(os.path.dirname(out), exist_ok=True)
        open(out, "w").write(table(t, cfg))
        print("wrote", out)


if __name__ == "__main__":
    main()
