"""The practice-and-composition table (2026-10-05, user: replaces the figure that paired rq2_skills and rq3_transfer).

One row per Qwen3.5-4B configuration (single agent / planner, untrained / trained). Left: success on the single-primitive
tasks of held-out sites per skill family and overall (task verifiers, three runs; the arms and runs of
docs/figures/rq2/rq2_config.yaml). Right: task success on the four benchmarks with significance stars (the arms, runs and
tests of docs/figures/rq3/rq3_config.yaml, so every number matches what the figures printed). Bold: best per column.

    python docs/figures/tables/make_practice_table.py [--out docs/paper/CVPR_current/tables/practice_table.tex]
"""
import argparse, os, statistics as st, sys
import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "common"))
sys.path.insert(0, os.path.join(HERE, "..", "rq3"))
from results import ROOT, task_rates, family_counts, primitive_filter  # noqa: E402
from make_rq3 import stars  # noqa: E402  (the figure's tests: paired permutation, exact McNemar on the live web)
sys.path.insert(0, ROOT)
from datagen.viewer import FAMILY_OF  # noqa: E402

FAMS = [("Drag & gesture", "Drag"), ("Reasoning base", "Reason"), ("Out-of-page I/O", "I/O"), ("Text entry", "Text"),
        ("Discrete selection", "Select"), ("Navigation", "Nav."), ("Form transaction", "Form")]   # order of the figure
BENCH_HEAD = {"miniweb": "Held-out", "wa": "WA-Lite", "wv": "WebVoyager", "om2w": "OM2W"}
LABEL = ["Single agent, untrained", "Single agent, trained", "Planner, untrained", r"\miniwebagent{}"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "docs", "paper", "CVPR_current", "tables", "practice_table.tex"))
    out = ap.parse_args().out
    c2 = yaml.safe_load(open(os.path.join(ROOT, "docs", "figures", "rq2", "rq2_config.yaml")))
    c3 = yaml.safe_load(open(os.path.join(ROOT, "docs", "figures", "rq3", "rq3_config.yaml")))
    only = primitive_filter(c2["task_sets"]["validation"].get("primitives"))
    benches = c3["benchmarks"]
    arms3 = c3["arms"]
    by3 = {a["label"]: a for a in arms3}
    rows = []
    for a2, a3 in zip(c2["arms"], arms3):                # both configs list the four arms in the same order
        fc = family_counts(a2["validation"], FAMILY_OF, only=only)
        fam = {f: 100 * fc[f][0] / fc[f][1] for f, _ in FAMS if fc.get(f, [0, 0])[1]}
        allp = st.mean(task_rates("miniweb", a2["validation"], only=only))
        task = {b["key"]: st.mean(task_rates(b["kind"], a3.get(b["key"]) or [], b.get("tasks"))) for b in benches}
        sig = {b["key"]: stars(b, by3[a3["compare"]], a3) if a3.get("compare") else "" for b in benches}
        rows.append(dict(fam=fam, all=allp, task=task, sig=sig))
    n_runs = len(c2["arms"][0]["validation"])
    fc0 = family_counts(c2["arms"][0]["validation"], FAMILY_OF, only=only)
    n_fam = {f: fc0[f][1] // n_runs for f, _ in FAMS}
    n_all = sum(n_fam.values())
    n_bench = {"miniweb": 63, "wa": 154, "wv": 536, "om2w": 280}

    best = lambda vals: max(vals)
    cols_fam = [[r["fam"][f] for r in rows] for f, _ in FAMS]
    col_all = [r["all"] for r in rows]
    cols_task = [[r["task"][b["key"]] for r in rows] for b in benches]
    bold = lambda v, col, fmt: (f"\\textbf{{{fmt.format(v)}}}" if abs(v - best(col)) < 1e-9 else fmt.format(v))

    L = ["% generated by docs/figures/tables/make_practice_table.py; do not edit by hand",
         "\\begin{table*}[t]", "\\centering", "\\footnotesize", "\\setlength{\\tabcolsep}{4.2pt}",
         "\\definecolor{mwagentrow}{HTML}{E6EDF6}",
         # an empty spacer column separates the two groups (so the highlighted row stays one continuous band)
         "\\begin{tabular}{@{}l" + "c" * len(FAMS) + "c@{}p{4pt}@{}" + "c" * len(benches) + "@{}}", "\\toprule",
         f" & \\multicolumn{{{len(FAMS) + 1}}}{{c}}{{Single primitives on held-out sites, by skill family (three runs)}}"
         f" & & \\multicolumn{{{len(benches)}}}{{c}}{{Task success (one run)}} \\\\",
         f"\\cmidrule(lr){{2-{len(FAMS) + 2}}}\\cmidrule(l){{{len(FAMS) + 4}-{len(FAMS) + 3 + len(benches)}}}",
         "Qwen3.5-4B & " + " & ".join(s for _, s in FAMS) + " & All & & " + " & ".join(BENCH_HEAD[b["key"]] for b in benches) + " \\\\",
         " & " + " & ".join(f"\\scriptsize({n_fam[f]})" for f, _ in FAMS) + f" & \\scriptsize({n_all}) & & "
         + " & ".join(f"\\scriptsize({n_bench[b['key']]})" for b in benches) + " \\\\", "\\midrule"]
    for i, (r, lab) in enumerate(zip(rows, LABEL)):
        cells = [bold(r["fam"][f], cols_fam[j], "{:.0f}") for j, (f, _) in enumerate(FAMS)]
        cells.append(bold(r["all"], col_all, "{:.1f}"))
        cells.append("")                                  # the spacer column
        for j, b in enumerate(benches):
            v = bold(r["task"][b["key"]], cols_task[j], "{:.1f}")
            cells.append(v + (f"$^{{{r['sig'][b['key']]}}}$" if r["sig"][b["key"]] else ""))
        pre = "\\rowcolor{mwagentrow}" if i == len(rows) - 1 else ""
        L.append(pre + lab + " & " + " & ".join(cells) + " \\\\")
    L += ["\\bottomrule", "\\end{tabular}",
          "\\caption{\\textbf{Practice improves every skill family, but only composition raises task success, on held-out sites "
          "and external benchmarks.} One Qwen3.5-4B as a single agent or as a planner, each untrained or with an executor "
          "trained on the 27.6K generated steps (the trained planner is \\miniwebagent{}). Single primitives: success (\\%) on the "
          "single-primitive tasks of held-out sites per skill family (abbreviated as in Tab.~\\ref{tab:rq1}; tasks in "
          "brackets; task verifiers). Task success: one run on each benchmark; stars: significance against the "
          "untrained single agent (trained single agent, untrained planner) or the untrained planner (\\miniwebagent{}); "
          "*: $p<0.05$, **: $p<0.01$, ***: $p<0.001$ (paired permutation test over tasks; exact McNemar test on the live "
          "web). Bold: best per column. \\textbf{Takeaway:} practice fixes skills that need one correct action, but trained "
          "skills pay off on tasks only when a planner composes them.}",
          "\\label{tab:practice}", "\\end{table*}", ""]
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w").write("\n".join(L))
    print("wrote", out)
    for r, lab in zip(rows, LABEL):
        print(f"  {lab:26s}", {s: round(r['fam'][f]) for f, s in FAMS}, "all", round(r["all"], 1),
              {k: (round(v, 1), r["sig"][k]) for k, v in r["task"].items()})


if __name__ == "__main__":
    main()
