"""Database schema for team-chat-workspace.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "channels": {
        "table_name": "team_chat_workspace_channels",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("is_private", "INTEGER NOT NULL DEFAULT 0"),
            ("created_by", "TEXT NOT NULL DEFAULT ''"),
            ("created_date", "TEXT NOT NULL DEFAULT ''"),
            ("member_count", "INTEGER NOT NULL DEFAULT 0"),
            ("topic", "TEXT NOT NULL DEFAULT ''"),
            ("pinned_count", "INTEGER NOT NULL DEFAULT 0"),
        ],
    },
    "messages": {
        "table_name": "team_chat_workspace_messages",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("channel_id", "TEXT NOT NULL DEFAULT ''"),
            ("user_id", "TEXT NOT NULL DEFAULT ''"),
            ("timestamp", "TEXT NOT NULL DEFAULT ''"),
            ("text", "TEXT NOT NULL DEFAULT ''"),
            ("edited", "INTEGER NOT NULL DEFAULT 0"),
            ("reactions_count", "INTEGER NOT NULL DEFAULT 0"),
            ("thread_count", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "timestamp",
            "user_id",
        ],
    },
    "reactions": {
        "table_name": "team_chat_workspace_reactions",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("message_id", "TEXT NOT NULL DEFAULT ''"),
            ("user_id", "TEXT NOT NULL DEFAULT ''"),
            ("emoji", "TEXT NOT NULL DEFAULT ''"),
            ("timestamp", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "timestamp",
            "user_id",
        ],
    },
    "threads": {
        "table_name": "team_chat_workspace_threads",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("parent_message_id", "TEXT NOT NULL DEFAULT ''"),
            ("channel_id", "TEXT NOT NULL DEFAULT ''"),
            ("topic", "TEXT NOT NULL DEFAULT ''"),
            ("replies", "TEXT NOT NULL DEFAULT ''"),
        ],
    },
    "users": {
        "table_name": "team_chat_workspace_users",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("display_name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
            ("status_emoji", "TEXT NOT NULL DEFAULT ''"),
            ("status_text", "TEXT NOT NULL DEFAULT ''"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("department", "TEXT NOT NULL DEFAULT ''"),
            ("timezone", "TEXT NOT NULL DEFAULT ''"),
            ("avatar_url", "TEXT NOT NULL DEFAULT ''"),
            ("joined_date", "TEXT NOT NULL DEFAULT ''"),
            ("last_active", "TEXT NOT NULL DEFAULT ''"),
            ("is_admin", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "department",
            "root_user_id",
            "status",
        ],
    },
}
