"""Database schema for forums.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "comments": {
        "table_name": "forums_comments",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("post_id", "TEXT NOT NULL DEFAULT ''"),
            ("author_root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("body", "TEXT NOT NULL DEFAULT ''"),
            ("score", "INTEGER NOT NULL DEFAULT 0"),
            ("parent_comment_id", "TEXT NOT NULL DEFAULT ''"),
            ("author", "TEXT NOT NULL DEFAULT ''"),
            ("created_utc", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "post_id",
            "author",
            "parent_comment_id",
        ],
    },
    "posts": {
        "table_name": "forums_posts",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("author_root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("subreddit", "TEXT NOT NULL DEFAULT ''"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("body", "TEXT NOT NULL DEFAULT ''"),
            ("score", "INTEGER NOT NULL DEFAULT 0"),
            ("num_comments", "INTEGER NOT NULL DEFAULT 0"),
            ("flair", "TEXT NOT NULL DEFAULT ''"),
            ("author", "TEXT NOT NULL DEFAULT ''"),
            ("created_utc", "TEXT NOT NULL DEFAULT ''"),
            ("url", "TEXT NOT NULL DEFAULT ''"),
            ("sticky", "TEXT NOT NULL DEFAULT ''"),
            ("locked", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "subreddit",
            "author",
        ],
    },
    "messages": {
        "table_name": "forums_messages",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("from_username", "TEXT NOT NULL DEFAULT ''"),
            ("to_username", "TEXT NOT NULL DEFAULT ''"),
            ("subject", "TEXT NOT NULL DEFAULT ''"),
            ("body", "TEXT NOT NULL DEFAULT ''"),
            ("created_utc", "TEXT NOT NULL DEFAULT ''"),
            ("read", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "to_username",
            "from_username",
        ],
    },
    "reddit_users": {
        "table_name": "forums_reddit_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("admin", "TEXT NOT NULL DEFAULT ''"),
            ("biography", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "created_at",
        ],
    },
    "subreddits": {
        "table_name": "forums_subreddits",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("sidebar", "TEXT NOT NULL DEFAULT ''"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("post_count", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "created_at",
        ],
    },
    "users": {
        "table_name": "forums_users",
        "columns": [
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("karma", "INTEGER NOT NULL DEFAULT 0"),
            ("subscribed_subreddits", "TEXT NOT NULL DEFAULT ''"),
            ("cake_day", "TEXT NOT NULL DEFAULT ''"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("id", "INTEGER PRIMARY KEY"),
            ("admin", "TEXT NOT NULL DEFAULT ''"),
            ("biography", "TEXT NOT NULL DEFAULT ''"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "created_at",
            "root_user_id",
        ],
    },
}
