"""Database schema for dating.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "likes": {
        "table_name": "dating_likes",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("from_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("to_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
            ("comment", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "date",
            "status",
        ],
    },
    "matches": {
        "table_name": "dating_matches",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user1_id", "INTEGER NOT NULL DEFAULT 0"),
            ("user2_id", "INTEGER NOT NULL DEFAULT 0"),
            ("matched_date", "TEXT NOT NULL DEFAULT ''"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
            ("notes", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "status",
        ],
    },
    "messages": {
        "table_name": "dating_messages",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("match_id", "INTEGER NOT NULL DEFAULT 0"),
            ("sender_id", "INTEGER NOT NULL DEFAULT 0"),
            ("content", "TEXT NOT NULL DEFAULT ''"),
            ("timestamp", "TEXT NOT NULL DEFAULT ''"),
            ("read", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "sender_id",
            "timestamp",
        ],
    },
    "users": {
        "table_name": "dating_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("age", "INTEGER NOT NULL DEFAULT 0"),
            ("gender", "TEXT NOT NULL DEFAULT ''"),
            ("bio", "TEXT NOT NULL DEFAULT ''"),
            ("location", "TEXT NOT NULL DEFAULT ''"),
            ("interests", "TEXT NOT NULL DEFAULT ''"),
            ("looking_for", "TEXT NOT NULL DEFAULT ''"),
            ("preferences", "TEXT NOT NULL DEFAULT ''"),
            ("photos", "TEXT NOT NULL DEFAULT ''"),
            ("verified", "INTEGER NOT NULL DEFAULT 0"),
            ("last_active", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "root_user_id",
        ],
    },
}
