"""Database schema for business-company.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "contacts": {
        "table_name": "business_company_contacts",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("company", "TEXT NOT NULL DEFAULT ''"),
            ("phone", "TEXT NOT NULL DEFAULT ''"),
            ("subject", "TEXT NOT NULL DEFAULT ''"),
            ("message", "TEXT NOT NULL DEFAULT ''"),
            ("submitted_at", "TEXT NOT NULL DEFAULT ''"),
            ("source", "TEXT NOT NULL DEFAULT ''"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
            ("assigned_to", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "status",
        ],
    },
    "jobs": {
        "table_name": "business_company_jobs",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("department", "TEXT NOT NULL DEFAULT ''"),
            ("location", "TEXT NOT NULL DEFAULT ''"),
            ("type", "TEXT NOT NULL DEFAULT ''"),
            ("posted_date", "TEXT NOT NULL DEFAULT ''"),
            ("salary_min", "INTEGER NOT NULL DEFAULT 0"),
            ("salary_max", "INTEGER NOT NULL DEFAULT 0"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("requirements", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "department",
            "type",
        ],
    },
    "posts": {
        "table_name": "business_company_posts",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("slug", "TEXT NOT NULL DEFAULT ''"),
            ("author", "TEXT NOT NULL DEFAULT ''"),
            ("author_id", "INTEGER NOT NULL DEFAULT 0"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("excerpt", "TEXT NOT NULL DEFAULT ''"),
            ("body", "TEXT NOT NULL DEFAULT ''"),
            ("tags", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "author_id",
            "category",
            "date",
        ],
    },
    "products": {
        "table_name": "business_company_products",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("price_monthly", "TEXT NOT NULL DEFAULT ''"),
            ("pricing_model", "TEXT NOT NULL DEFAULT ''"),
            ("launched_year", "INTEGER NOT NULL DEFAULT 0"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
            ("features", "TEXT NOT NULL DEFAULT ''"),
            ("is_featured", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "category",
            "status",
        ],
    },
    "services": {
        "table_name": "business_company_services",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("engagement_model", "TEXT NOT NULL DEFAULT ''"),
            ("typical_duration", "TEXT NOT NULL DEFAULT ''"),
            ("includes", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "category",
        ],
    },
    "subscribers": {
        "table_name": "business_company_subscribers",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("company", "TEXT NOT NULL DEFAULT ''"),
            ("subscribed_topics", "TEXT NOT NULL DEFAULT ''"),
            ("subscribed_at", "TEXT NOT NULL DEFAULT ''"),
            ("active", "INTEGER NOT NULL DEFAULT 0"),
        ],
    },
    "team": {
        "table_name": "business_company_team",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("department", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("phone", "TEXT NOT NULL DEFAULT ''"),
            ("bio", "TEXT NOT NULL DEFAULT ''"),
            ("start_year", "INTEGER NOT NULL DEFAULT 0"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("linkedin", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "department",
            "root_user_id",
        ],
    },
    "testimonials": {
        "table_name": "business_company_testimonials",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("text", "TEXT NOT NULL DEFAULT ''"),
            ("author", "TEXT NOT NULL DEFAULT ''"),
            ("role", "TEXT NOT NULL DEFAULT ''"),
            ("company", "TEXT NOT NULL DEFAULT ''"),
            ("product", "TEXT NOT NULL DEFAULT ''"),
            ("rating", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "role",
        ],
    },
}
