"""Database schema for crowdfunding-donations.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "campaigns": {
        "table_name": "crowdfunding_donations_campaigns",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("creator_id", "INTEGER NOT NULL DEFAULT 0"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("goal_amount", "INTEGER NOT NULL DEFAULT 0"),
            ("raised_amount", "INTEGER NOT NULL DEFAULT 0"),
            ("backer_count", "INTEGER NOT NULL DEFAULT 0"),
            ("funding_model", "TEXT NOT NULL DEFAULT ''"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
            ("start_date", "TEXT NOT NULL DEFAULT ''"),
            ("end_date", "TEXT NOT NULL DEFAULT ''"),
            ("reward_tiers", "TEXT NOT NULL DEFAULT ''"),
            ("updates", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "category",
            "creator_id",
            "status",
        ],
    },
    "pledges": {
        "table_name": "crowdfunding_donations_pledges",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("campaign_id", "INTEGER NOT NULL DEFAULT 0"),
            ("amount", "INTEGER NOT NULL DEFAULT 0"),
            ("tier_id", "INTEGER NOT NULL DEFAULT 0"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "campaign_id",
            "date",
            "status",
            "user_id",
        ],
    },
    "users": {
        "table_name": "crowdfunding_donations_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("backed_campaigns", "TEXT NOT NULL DEFAULT ''"),
            ("created_campaigns", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "root_user_id",
        ],
    },
}
