"""Database schema for instant-messaging.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "conversations": {
        "table_name": "instant_messaging_conversations",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("type", "TEXT NOT NULL DEFAULT ''"),
            ("participants", "TEXT NOT NULL DEFAULT ''"),
            ("participant_names", "TEXT NOT NULL DEFAULT ''"),
            ("created", "TEXT NOT NULL DEFAULT ''"),
            ("last_message", "TEXT NOT NULL DEFAULT ''"),
            ("message_count", "INTEGER NOT NULL DEFAULT 0"),
            ("pinned_count", "INTEGER NOT NULL DEFAULT 0"),
            ("muted", "INTEGER NOT NULL DEFAULT 0"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("group_photo", "TEXT NOT NULL DEFAULT ''"),
            ("admin", "TEXT NOT NULL DEFAULT ''"),
            ("note", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "type",
        ],
    },
    "media": {
        "table_name": "instant_messaging_media",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("conversation_id", "TEXT NOT NULL DEFAULT ''"),
            ("sender_id", "TEXT NOT NULL DEFAULT ''"),
            ("timestamp", "TEXT NOT NULL DEFAULT ''"),
            ("type", "TEXT NOT NULL DEFAULT ''"),
            ("mime_type", "TEXT NOT NULL DEFAULT ''"),
            ("file_name", "TEXT NOT NULL DEFAULT ''"),
            ("file_path", "TEXT NOT NULL DEFAULT ''"),
            ("file_size_bytes", "INTEGER NOT NULL DEFAULT 0"),
            ("caption", "TEXT NOT NULL DEFAULT ''"),
            ("thumbnail_path", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "sender_id",
            "timestamp",
            "type",
        ],
    },
    "messages": {
        "table_name": "instant_messaging_messages",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("conversation_id", "TEXT NOT NULL DEFAULT ''"),
            ("sender_id", "TEXT NOT NULL DEFAULT ''"),
            ("timestamp", "TEXT NOT NULL DEFAULT ''"),
            ("text", "TEXT NOT NULL DEFAULT ''"),
            ("read", "INTEGER NOT NULL DEFAULT 0"),
            ("media_id", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "sender_id",
            "timestamp",
        ],
    },
    "users": {
        "table_name": "instant_messaging_users",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("display_name", "TEXT NOT NULL DEFAULT ''"),
            ("phone", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
            ("last_seen", "TEXT NOT NULL DEFAULT ''"),
            ("profile_photo", "TEXT NOT NULL DEFAULT ''"),
            ("about", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "root_user_id",
            "status",
        ],
    },
}
