"""Database schema for ai-chatbots.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "conversations": {
        "table_name": "ai_chatbots_conversations",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("bot", "TEXT NOT NULL DEFAULT ''"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("updated_at", "TEXT NOT NULL DEFAULT ''"),
            ("messages", "TEXT NOT NULL DEFAULT ''"),
            ("shared", "INTEGER NOT NULL DEFAULT 0"),
            ("archived", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "created_at",
            "updated_at",
            "user_id",
        ],
    },
    "faq": {
        "table_name": "ai_chatbots_faq",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("question", "TEXT NOT NULL DEFAULT ''"),
            ("answer", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "category",
        ],
    },
    "knowledge_base": {
        "table_name": "ai_chatbots_knowledge_base",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("topic", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("keywords", "TEXT NOT NULL DEFAULT ''"),
            ("content", "TEXT NOT NULL DEFAULT ''"),
            ("follow_up", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "category",
        ],
    },
    "prompts_library": {
        "table_name": "ai_chatbots_prompts_library",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("prompt", "TEXT NOT NULL DEFAULT ''"),
            ("tags", "TEXT NOT NULL DEFAULT ''"),
            ("popularity", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "category",
        ],
    },
    "users": {
        "table_name": "ai_chatbots_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("display_name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("preferences", "TEXT NOT NULL DEFAULT ''"),
            ("subscription", "TEXT NOT NULL DEFAULT ''"),
            ("saved_prompts", "TEXT NOT NULL DEFAULT ''"),
            ("shared_conversations", "TEXT NOT NULL DEFAULT ''"),
            ("avatar", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "root_user_id",
        ],
    },
}
