"""Database schema for multimedia-posting.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "comments": {
        "table_name": "multimedia_posting_comments",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("post_id", "TEXT NOT NULL DEFAULT ''"),
            ("author_id", "TEXT NOT NULL DEFAULT ''"),
            ("text", "TEXT NOT NULL DEFAULT ''"),
            ("likes_count", "INTEGER NOT NULL DEFAULT 0"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("reply_to", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "author_id",
            "created_at",
            "post_id",
        ],
    },
    "follows": {
        "table_name": "multimedia_posting_follows",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("follower_id", "TEXT NOT NULL DEFAULT ''"),
            ("following_id", "TEXT NOT NULL DEFAULT ''"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "created_at",
        ],
    },
    "posts": {
        "table_name": "multimedia_posting_posts",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("author_id", "TEXT NOT NULL DEFAULT ''"),
            ("type", "TEXT NOT NULL DEFAULT ''"),
            ("image_url", "TEXT NOT NULL DEFAULT ''"),
            ("caption", "TEXT NOT NULL DEFAULT ''"),
            ("location", "TEXT NOT NULL DEFAULT ''"),
            ("likes_count", "INTEGER NOT NULL DEFAULT 0"),
            ("comments_count", "INTEGER NOT NULL DEFAULT 0"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("tags", "TEXT NOT NULL DEFAULT ''"),
            ("additional_images", "TEXT NOT NULL DEFAULT ''"),
            ("video_url", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "author_id",
            "created_at",
            "type",
        ],
    },
    "stories": {
        "table_name": "multimedia_posting_stories",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("author_id", "TEXT NOT NULL DEFAULT ''"),
            ("type", "TEXT NOT NULL DEFAULT ''"),
            ("media_url", "TEXT NOT NULL DEFAULT ''"),
            ("caption", "TEXT NOT NULL DEFAULT ''"),
            ("views_count", "INTEGER NOT NULL DEFAULT 0"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("expires_at", "TEXT NOT NULL DEFAULT ''"),
            ("is_active", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "author_id",
            "created_at",
            "type",
        ],
    },
    "users": {
        "table_name": "multimedia_posting_users",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("handle", "TEXT NOT NULL DEFAULT ''"),
            ("display_name", "TEXT NOT NULL DEFAULT ''"),
            ("bio", "TEXT NOT NULL DEFAULT ''"),
            ("avatar_url", "TEXT NOT NULL DEFAULT ''"),
            ("followers_count", "INTEGER NOT NULL DEFAULT 0"),
            ("following_count", "INTEGER NOT NULL DEFAULT 0"),
            ("posts_count", "INTEGER NOT NULL DEFAULT 0"),
            ("is_verified", "INTEGER NOT NULL DEFAULT 0"),
            ("is_private", "INTEGER NOT NULL DEFAULT 0"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("last_active", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "created_at",
            "root_user_id",
        ],
    },
}
