"""Database schema for ticketing-events.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "events": {
        "table_name": "ticketing_events_events",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("venue", "TEXT NOT NULL DEFAULT ''"),
            ("address", "TEXT NOT NULL DEFAULT ''"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("time", "TEXT NOT NULL DEFAULT ''"),
            ("doors_open", "TEXT NOT NULL DEFAULT ''"),
            ("organizer", "TEXT NOT NULL DEFAULT ''"),
            ("ticket_types", "TEXT NOT NULL DEFAULT ''"),
            ("age_restriction", "TEXT NOT NULL DEFAULT ''"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
            ("image_url", "TEXT NOT NULL DEFAULT ''"),
            ("tags", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "category",
            "date",
            "status",
        ],
    },
    "orders": {
        "table_name": "ticketing_events_orders",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("event_id", "INTEGER NOT NULL DEFAULT 0"),
            ("event_name", "TEXT NOT NULL DEFAULT ''"),
            ("tickets", "TEXT NOT NULL DEFAULT ''"),
            ("quantity", "INTEGER NOT NULL DEFAULT 0"),
            ("subtotal", "REAL NOT NULL DEFAULT 0.0"),
            ("fees", "REAL NOT NULL DEFAULT 0.0"),
            ("total", "REAL NOT NULL DEFAULT 0.0"),
            ("payment_method", "TEXT NOT NULL DEFAULT ''"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
            ("ordered_at", "TEXT NOT NULL DEFAULT ''"),
            ("confirmation_email_sent", "INTEGER NOT NULL DEFAULT 0"),
            ("refund_amount", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "status",
            "user_id",
        ],
    },
    "tickets": {
        "table_name": "ticketing_events_tickets",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("order_id", "TEXT NOT NULL DEFAULT ''"),
            ("event_id", "INTEGER NOT NULL DEFAULT 0"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("ticket_type", "TEXT NOT NULL DEFAULT ''"),
            ("price", "REAL NOT NULL DEFAULT 0.0"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
            ("barcode", "TEXT NOT NULL DEFAULT ''"),
            ("seat", "TEXT NOT NULL DEFAULT ''"),
            ("purchased_at", "TEXT NOT NULL DEFAULT ''"),
            ("checked_in_at", "TEXT NOT NULL DEFAULT ''"),
            ("attendee_name", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "status",
            "user_id",
        ],
    },
    "users": {
        "table_name": "ticketing_events_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("display_name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("phone", "TEXT NOT NULL DEFAULT ''"),
            ("joined_date", "TEXT NOT NULL DEFAULT ''"),
            ("location", "TEXT NOT NULL DEFAULT ''"),
            ("payment_methods", "TEXT NOT NULL DEFAULT ''"),
            ("notification_preferences", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "root_user_id",
        ],
    },
}
