"""Database schema for version-control.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "activities": {
        "table_name": "version_control_activities",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("type", "TEXT NOT NULL DEFAULT ''"),
            ("author_root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("gitlab_username", "TEXT NOT NULL DEFAULT ''"),
            ("repo", "TEXT NOT NULL DEFAULT ''"),
            ("branch", "TEXT NOT NULL DEFAULT ''"),
            ("commit_sha", "TEXT NOT NULL DEFAULT ''"),
            ("commit_message", "TEXT NOT NULL DEFAULT ''"),
            ("files_changed", "INTEGER NOT NULL DEFAULT 0"),
            ("additions", "INTEGER NOT NULL DEFAULT 0"),
            ("deletions", "INTEGER NOT NULL DEFAULT 0"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("merge_request_id", "INTEGER NOT NULL DEFAULT 0"),
            ("merge_request_title", "TEXT NOT NULL DEFAULT ''"),
            ("target_branch", "TEXT NOT NULL DEFAULT ''"),
            ("source_branch", "TEXT NOT NULL DEFAULT ''"),
            ("submitted_by_root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("review_state", "TEXT NOT NULL DEFAULT ''"),
            ("review_comment", "TEXT NOT NULL DEFAULT ''"),
            ("commits_count", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "created_at",
            "type",
        ],
    },
    "issues_raw": {
        "table_name": "version_control_issues_raw",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("state_id", "INTEGER NOT NULL DEFAULT 0"),
            ("author_id", "INTEGER NOT NULL DEFAULT 0"),
            ("project_name", "TEXT NOT NULL DEFAULT ''"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("updated_at", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "author_id",
            "created_at",
            "updated_at",
        ],
    },
    "labels_raw": {
        "table_name": "version_control_labels_raw",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("color", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("project_name", "TEXT NOT NULL DEFAULT ''"),
            ("type", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "type",
        ],
    },
    "merge_requests_raw": {
        "table_name": "version_control_merge_requests_raw",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("state_id", "INTEGER NOT NULL DEFAULT 0"),
            ("author_id", "INTEGER NOT NULL DEFAULT 0"),
            ("project_name", "TEXT NOT NULL DEFAULT ''"),
            ("source_branch", "TEXT NOT NULL DEFAULT ''"),
            ("target_branch", "TEXT NOT NULL DEFAULT ''"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("updated_at", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "author_id",
            "created_at",
            "updated_at",
        ],
    },
    "notes_raw": {
        "table_name": "version_control_notes_raw",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("note", "TEXT NOT NULL DEFAULT ''"),
            ("noteable_type", "TEXT NOT NULL DEFAULT ''"),
            ("noteable_id", "INTEGER NOT NULL DEFAULT 0"),
            ("author_id", "INTEGER NOT NULL DEFAULT 0"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("updated_at", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "author_id",
            "created_at",
            "updated_at",
        ],
    },
    "projects_raw": {
        "table_name": "version_control_projects_raw",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("namespace", "TEXT NOT NULL DEFAULT ''"),
            ("visibility_level", "INTEGER NOT NULL DEFAULT 0"),
            ("star_count", "INTEGER NOT NULL DEFAULT 0"),
            ("last_activity_at", "TEXT NOT NULL DEFAULT ''"),
            ("creator_id", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "creator_id",
        ],
    },
    "repositories": {
        "table_name": "version_control_repositories",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("namespace", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("default_branch", "TEXT NOT NULL DEFAULT ''"),
            ("forks", "INTEGER NOT NULL DEFAULT 0"),
            ("tech_stack", "TEXT NOT NULL DEFAULT ''"),
            ("star_count", "INTEGER NOT NULL DEFAULT 0"),
            ("visibility_level", "TEXT NOT NULL DEFAULT ''"),
            ("last_activity_at", "TEXT NOT NULL DEFAULT ''"),
            ("creator_id", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "creator_id",
        ],
    },
    "users": {
        "table_name": "version_control_users",
        "columns": [
            ("row_id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("role", "TEXT NOT NULL DEFAULT ''"),
            ("groups", "TEXT NOT NULL DEFAULT ''"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "created_at",
            "role",
            "root_user_id",
        ],
    },
    "users_raw": {
        "table_name": "version_control_users_raw",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("sign_in_count", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "created_at",
        ],
    },
}
