"""Database schema for rating-review.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "businesses": {
        "table_name": "rating_review_businesses",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("subcategory", "TEXT NOT NULL DEFAULT ''"),
            ("address", "TEXT NOT NULL DEFAULT ''"),
            ("phone", "TEXT NOT NULL DEFAULT ''"),
            ("website", "TEXT NOT NULL DEFAULT ''"),
            ("hours", "TEXT NOT NULL DEFAULT ''"),
            ("price_range", "TEXT NOT NULL DEFAULT ''"),
            ("overall_rating", "REAL NOT NULL DEFAULT 0.0"),
            ("review_count", "INTEGER NOT NULL DEFAULT 0"),
            ("claimed", "INTEGER NOT NULL DEFAULT 0"),
            ("attributes", "TEXT NOT NULL DEFAULT ''"),
            ("coordinates", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "category",
        ],
    },
    "photos": {
        "table_name": "rating_review_photos",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("review_id", "INTEGER NOT NULL DEFAULT 0"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("business_id", "INTEGER NOT NULL DEFAULT 0"),
            ("caption", "TEXT NOT NULL DEFAULT ''"),
            ("url", "TEXT NOT NULL DEFAULT ''"),
            ("uploaded_at", "TEXT NOT NULL DEFAULT ''"),
            ("width", "INTEGER NOT NULL DEFAULT 0"),
            ("height", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "user_id",
        ],
    },
    "reviews": {
        "table_name": "rating_review_reviews",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("business_id", "INTEGER NOT NULL DEFAULT 0"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("rating", "INTEGER NOT NULL DEFAULT 0"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("text", "TEXT NOT NULL DEFAULT ''"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("useful_count", "INTEGER NOT NULL DEFAULT 0"),
            ("funny_count", "INTEGER NOT NULL DEFAULT 0"),
            ("cool_count", "INTEGER NOT NULL DEFAULT 0"),
            ("photos", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "date",
            "user_id",
        ],
    },
    "users": {
        "table_name": "rating_review_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("display_name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("avatar_url", "TEXT NOT NULL DEFAULT ''"),
            ("joined_date", "TEXT NOT NULL DEFAULT ''"),
            ("location", "TEXT NOT NULL DEFAULT ''"),
            ("review_count", "INTEGER NOT NULL DEFAULT 0"),
            ("photo_count", "INTEGER NOT NULL DEFAULT 0"),
            ("friends_count", "INTEGER NOT NULL DEFAULT 0"),
            ("elite_status", "INTEGER NOT NULL DEFAULT 0"),
            ("is_verified", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "root_user_id",
        ],
    },
}
