"""Expand transit-directions (Lakeport Transit Authority) base data.

The site ships with 848 rows total (schedules: 629, stops: 171, routes: 30,
trip_plans: 8, routes_transit: 6, plus users/fares). The bulk of the expansion
goes into `schedules` (GTFS-style stop_times): each of the 29 routes with
existing trips gets many more service runs through the day, generated by
replaying the route's existing trip patterns (same stop_id/stop_name/sequence,
same inter-stop offsets) at new seeded departure times. Also adds ~280 new
street-corner stops in the existing Lakeport naming style and 24 saved trip
plans for the three existing users, reusing the routes_transit vocabulary.

Referential integrity: new schedule rows only reference existing route_id /
stop_id / stop_name triples taken verbatim from existing trips; trip plans
reference existing users and Route 1-6X names. Per-route schedule row counts
stay under ~200 so the /route/<id> detail pages remain small.

Insert-only -- existing rows are never touched. Inserted ids are recorded in
data/backups/transit-directions-expansion-2026-07-20/inserted_ids.json.

Usage: ~/.conda/envs/miniweb/bin/python scripts/expand_transit_directions_data.py [--dry-run]
"""
import json
import random
import sqlite3
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB_PATH = ROOT / "data" / "trimmed_miniweb.db"
BACKUP_DIR = ROOT / "data" / "backups" / "transit-directions-expansion-2026-07-20"

rng = random.Random(20260720)

DRY_RUN = "--dry-run" in sys.argv

# ---------------------------------------------------------------------------
# Vocabulary (matches existing Lakeport / Portland-grid naming in stops table)
# ---------------------------------------------------------------------------

MAIN_STREETS = [
    "Fessenden", "Lombard", "Willamette Blvd", "Lakeview Blvd", "Main St",
    "Harbor Dr", "Cedar Blvd", "Oak Ave", "Maple Ln", "Interstate Ave",
    "Greeley Ave", "Rosa Parks Way", "Killingsworth", "Alberta St",
    "Prescott St", "Fremont St", "Broadway", "Weidler St", "Halsey St",
    "Glisan St", "Burnside St", "Stark St", "Belmont St", "Hawthorne Blvd",
    "Division St", "Powell Blvd", "Holgate Blvd", "Foster Rd", "Woodstock Blvd",
]
CROSS_STREETS = [
    "Oak Ave", "Pine Rd", "Elm Dr", "Birch Ct", "Spruce Way", "Vine St",
    "Haven", "Portsmouth", "Van Houten", "Geneva", "Dwight", "Chautauqua",
    "Wall", "Woolsey", "Buchanan", "Charleston", "Ida", "Tyler", "Drummond",
    "Vancouver Ave", "Williams Ave", "Mississippi Ave", "Albina Ave",
    "Michigan Ave", "Montana Ave", "Gantenbein", "Kerby Ave", "Commercial Ave",
    "7th Ave", "9th Ave", "11th Ave", "15th Ave", "20th Ave", "24th Ave",
    "28th Ave", "33rd Ave", "39th Ave", "42nd Ave", "47th Ave", "52nd Ave",
    "60th Ave", "67th Ave", "72nd Ave", "78th Ave", "82nd Ave", "87th Ave",
    "92nd Ave", "96th Ave", "101st Ave", "104th Ave", "108th Ave", "112th Ave",
    "117th Ave", "122nd Ave", "125th Ave", "130th Ave", "136th Ave",
    "141st Ave", "145th Ave", "148th Ave", "154th Ave", "162nd Ave",
]
DIR_PREFIXES = ["N", "NE", "SE", "SW", "NW", ""]

# routes_transit vocabulary for saved trip plans (route id -> data)
RT_ROUTES = {
    1: ("Route 1 - Downtown - Harbor",
        [("Lakeport Transit Center", "LTC-001"), ("Main St & Oak Ave", "LTC-002"),
         ("Main St & Cedar Blvd", "LTC-003"), ("Harbor Dr & Civic Center", "LTC-004"),
         ("Harbor Marina", "LTC-005")], 25),
    2: ("Route 2 - Main St - Innovation Way",
        [("Maple Ln & Pine Rd", "LTC-007"), ("Oak Ave & Birch Ct", "LTC-008"),
         ("Main St & Library", "LTC-009"), ("Main St & Elm Dr", "LTC-010"),
         ("Innovation Way Campus", "LTC-006")], 22),
    3: ("Route 3 - Cedar Blvd - Academic Dr",
        [("Cedar Blvd & Harbor Dr", "LTC-012"), ("Cedar Blvd & Elm Dr", "LTC-015"),
         ("Cedar Blvd & Main St", "LTC-013"), ("Lakeport High School", "LTC-017"),
         ("Academic Dr & Pine Rd", "LTC-018")], 20),
    4: ("Route 4 - Oak Ave - Medical Center",
        [("Oak Ave & Maple Ln", "LTC-020"), ("Oak Ave & Main St", "LTC-021"),
         ("Oak Ave & Spruce Way", "LTC-022"), ("Health Plaza & Cedar Blvd", "LTC-023"),
         ("Lakeport Medical Center", "LTC-024")], 18),
    5: ("Route 5 - Maple Ln Loop",
        [("Maple Ln & Pine Rd", "LTC-007"), ("Maple Ln Bakery", "LTC-026"),
         ("Oak Ave & Main St", "LTC-021"), ("Liberty Park", "LTC-027"),
         ("Civic Center Dr", "LTC-028"), ("Main St & Spruce Way", "LTC-029")], 35),
    6: ("Route 6X - Express to Seattle",
        [("Lakeport Transit Center", "LTC-001"), ("Innovation Way Campus", "LTC-006"),
         ("Federal Way TC", "LTC-030"), ("Seattle King Street Station", "LTC-031")], 55),
}

PLAN_DESTS = [
    ("Harbor Marina farmers market", "88 Harbor Dr, Lakeport, WA 98401", 1),
    ("Civic Center library run", "210 Civic Center Dr, Lakeport, WA 98401", 1),
    ("Lakeport Medical Center appointment", "900 Health Plaza, Lakeport, WA 98401", 4),
    ("Liberty Park weekend loop", "45 Liberty Park Way, Lakeport, WA 98401", 5),
    ("Maple Ln Bakery breakfast", "1180 Maple Ln, Lakeport, WA 98401", 5),
    ("Seattle day trip", "303 S Jackson St, Seattle, WA 98104", 6),
    ("Lakeport High School volunteering", "1600 Academic Dr, Lakeport, WA 98401", 3),
    ("Innovation Way client visit", "520 Innovation Way, Lakeport, WA 98401", 2),
    ("Downtown errands", "300 Main St, Lakeport, WA 98401", 1),
    ("Cedar Blvd dentist", "740 Cedar Blvd, Lakeport, WA 98401", 3),
    ("Harbor Dr waterfront walk", "12 Harbor Dr, Lakeport, WA 98401", 1),
    ("Academic Dr evening class", "1750 Academic Dr, Lakeport, WA 98401", 3),
]

USER_HOMES = {
    1: ("Alex", "1247 Maple Ln, Lakeport, WA 98401", "Maple Ln & Pine Rd", "LTC-007"),
    2: ("Natalie", "945 Elm Dr, Apt 4B, Lakeport, WA 98401", "Main St & Elm Dr", "LTC-010"),
    3: ("Elena", "2200 Birch Ct, Lakeport, WA 98401", "Oak Ave & Birch Ct", "LTC-008"),
}

NOTES = [
    "Leave a few minutes early on rainy days.",
    "Bus is usually on time; stop has a shelter.",
    "Transfer is tight -- take the earlier run if possible.",
    "Weekend service runs every 20-30 minutes on this route.",
    "Saved after trying this route once; worked well.",
    "Off-peak trip, plenty of seats.",
    "Good option when the car is in the shop.",
    "Monthly pass covers this whole trip.",
]


def hms_to_sec(t):
    h, m, s = (int(x) for x in t.split(":"))
    return h * 3600 + m * 60 + s


def sec_to_hms(sec):
    return "%02d:%02d:%02d" % (sec // 3600, (sec % 3600) // 60, sec % 60)


def main():
    conn = sqlite3.connect(DB_PATH, timeout=60)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()

    inserted = {"transit_directions_schedules": [],
                "transit_directions_stops": [],
                "transit_directions_trip_plans": []}

    # -------------------------------------------------------------------
    # 1. Schedules: replay existing trip patterns at new times
    # -------------------------------------------------------------------
    max_sched_id = cur.execute(
        "SELECT MAX(id) FROM transit_directions_schedules").fetchone()[0]
    existing_trip_ids = {r[0] for r in cur.execute(
        "SELECT DISTINCT trip_id FROM transit_directions_schedules")}

    patterns = defaultdict(list)  # route_id -> [pattern]; pattern = list of rows
    for r in cur.execute(
            "SELECT route_id, stop_id, stop_name, arrival, departure, sequence, trip_id "
            "FROM transit_directions_schedules ORDER BY trip_id, sequence"):
        patterns_key = (r["route_id"], r["trip_id"])
        patterns[patterns_key].append(dict(r))

    by_route = defaultdict(list)
    for (route_id, _trip), rows in sorted(patterns.items()):
        by_route[route_id].append(rows)

    sched_rows = []
    next_id = max_sched_id + 1
    next_trip = 17500000
    TARGET_ROWS_PER_ROUTE = 135  # added rows per route -> route pages stay small

    for route_id in sorted(by_route):
        pats = by_route[route_id]
        added = 0
        # round-robin over the route's existing trip patterns
        pi = 0
        # seeded departure times spread across the service day
        while added < TARGET_ROWS_PER_ROUTE:
            pat = pats[pi % len(pats)]
            pi += 1
            base_old = hms_to_sec(pat[0]["arrival"])
            span = hms_to_sec(pat[-1]["arrival"]) - base_old
            # new first-stop time between 5:00 and as late as fits before 23:59
            latest = 23 * 3600 + 59 * 60 - max(span, 0)
            new_base = rng.randrange(5 * 3600, max(latest, 5 * 3600 + 60), 60)
            new_base += rng.randrange(0, 60)  # seconds jitter like existing data
            while str(next_trip) in existing_trip_ids:
                next_trip += 1
            trip_id = str(next_trip)
            next_trip += 1
            for row in pat:
                t = sec_to_hms(new_base + (hms_to_sec(row["arrival"]) - base_old))
                sched_rows.append((next_id, route_id, row["stop_id"],
                                   row["stop_name"], t, t, row["sequence"], trip_id))
                inserted["transit_directions_schedules"].append(next_id)
                next_id += 1
                added += 1

    # -------------------------------------------------------------------
    # 2. Stops: new street-corner stops in the existing naming style
    # -------------------------------------------------------------------
    existing_names = {r[0] for r in cur.execute(
        "SELECT name FROM transit_directions_stops")}
    existing_codes = {r[0] for r in cur.execute(
        "SELECT stop_code FROM transit_directions_stops")}
    max_stop_id = cur.execute(
        "SELECT MAX(id) FROM transit_directions_stops").fetchone()[0]

    stop_rows = []
    sid = max_stop_id + 1
    used_names = set()
    attempts = 0
    while len(stop_rows) < 280 and attempts < 20000:
        attempts += 1
        main = rng.choice(MAIN_STREETS)
        cross = rng.choice(CROSS_STREETS)
        if main == cross:
            continue
        name = f"{main} & {cross}"
        if name in existing_names or name in used_names:
            continue
        used_names.add(name)
        code = str(rng.randrange(1000, 13000))
        while code in existing_codes:
            code = str(rng.randrange(1000, 13000))
        existing_codes.add(code)
        prefix = rng.choice(DIR_PREFIXES)
        address = (f"{prefix} {main} & {cross}, Lakeport" if prefix
                   else f"{main} & {cross}, Lakeport")
        lat = round(rng.uniform(45.468, 45.597), 6)
        lng = round(rng.uniform(-122.801, -122.558), 6)
        stop_rows.append((sid, name, code, address, lat, lng, "[]", "[]", 1, "B"))
        inserted["transit_directions_stops"].append(sid)
        sid += 1

    # -------------------------------------------------------------------
    # 3. Trip plans: saved plans for the three existing users
    # -------------------------------------------------------------------
    max_plan_id = cur.execute(
        "SELECT MAX(id) FROM transit_directions_trip_plans").fetchone()[0]
    plan_rows = []
    pid = max_plan_id + 1
    freqs = ["daily", "weekly", "occasional", "rare"]
    for i in range(24):
        user_id = (i % 3) + 1
        first_name, home, home_stop, home_code = USER_HOMES[user_id]
        label, dest_addr, rt_id = PLAN_DESTS[i % len(PLAN_DESTS)]
        route_name, stops_list, travel = RT_ROUTES[rt_id]
        board = rng.choice(stops_list[:2])
        alight = stops_list[-1]
        walk1 = rng.randint(3, 7)
        walk2 = rng.randint(2, 6)
        dep_h = rng.randint(7, 19)
        dep_m = rng.choice([0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])
        total = walk1 + travel + walk2
        dep = f"{dep_h:02d}:{dep_m:02d}"
        arr_min = dep_h * 60 + dep_m + total
        arr = f"{(arr_min // 60) % 24:02d}:{arr_min % 60:02d}"
        bus_dep_min = dep_h * 60 + dep_m + walk1
        bus_arr_min = bus_dep_min + travel
        legs = [
            {"type": "walk", "from": home.split(",")[0],
             "to": f"{board[0]} (Stop {board[1]})",
             "duration_minutes": walk1, "distance_km": round(walk1 * 0.065, 1)},
            {"type": "bus", "route": route_name,
             "from_stop": board[0], "to_stop": alight[0],
             "departure": f"{(bus_dep_min // 60) % 24:02d}:{bus_dep_min % 60:02d}",
             "arrival": f"{(bus_arr_min // 60) % 24:02d}:{bus_arr_min % 60:02d}",
             "duration_minutes": travel,
             "stops_count": rng.randint(2, len(stops_list))},
            {"type": "walk", "from": f"{alight[0]} (Stop {alight[1]})",
             "to": dest_addr.split(",")[0],
             "duration_minutes": walk2, "distance_km": round(walk2 * 0.065, 1)},
        ]
        fare = 3.5 if rt_id == 6 else 2.5
        year = rng.choice([2023, 2023, 2024, 2024, 2025])
        saved = f"{year}-{rng.randint(1, 12):02d}-{rng.randint(1, 28):02d}"
        plan_rows.append((pid, user_id, f"{first_name}: {label}", home, dest_addr,
                          dep, arr, total, json.dumps(legs), fare, saved,
                          rng.choice(freqs), rng.choice(NOTES)))
        inserted["transit_directions_trip_plans"].append(pid)
        pid += 1

    # -------------------------------------------------------------------
    # Report / insert
    # -------------------------------------------------------------------
    print(f"schedules to insert:  {len(sched_rows)}")
    print(f"stops to insert:      {len(stop_rows)}")
    print(f"trip_plans to insert: {len(plan_rows)}")

    if DRY_RUN:
        print("\n-- dry run, nothing written. Samples:")
        for r in sched_rows[:3]:
            print("  sched:", r)
        for r in stop_rows[:3]:
            print("  stop: ", r)
        print("  plan: ", plan_rows[0][:8])
        conn.close()
        return

    cur.executemany(
        "INSERT INTO transit_directions_schedules "
        "(id, route_id, stop_id, stop_name, arrival, departure, sequence, trip_id) "
        "VALUES (?,?,?,?,?,?,?,?)", sched_rows)
    cur.executemany(
        "INSERT INTO transit_directions_stops "
        "(id, name, stop_code, address, lat, lng, routes_served, amenities, "
        "wheelchair_accessible, zone) VALUES (?,?,?,?,?,?,?,?,?,?)", stop_rows)
    cur.executemany(
        "INSERT INTO transit_directions_trip_plans "
        "(id, user_id, name, origin, destination, departure_time, arrival_time, "
        "total_duration_minutes, legs, fare, saved_date, frequency, notes) "
        "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)", plan_rows)

    # FTS rebuild for touched tables that have content-linked FTS indexes
    cur.execute("INSERT INTO fts_transit_directions_schedules"
                "(fts_transit_directions_schedules) VALUES('rebuild')")
    cur.execute("INSERT INTO fts_transit_directions_stops"
                "(fts_transit_directions_stops) VALUES('rebuild')")

    conn.commit()

    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    (BACKUP_DIR / "inserted_ids.json").write_text(json.dumps(inserted, indent=1))

    total = 0
    for t in ["schedules", "stops", "routes", "routes_transit", "trip_plans",
              "users", "fares"]:
        n = cur.execute(f"SELECT COUNT(*) FROM transit_directions_{t}").fetchone()[0]
        total += n
        print(f"  transit_directions_{t}: {n}")
    print(f"site total: {total}")
    print(f"inserted; rollback ids at {BACKUP_DIR}/inserted_ids.json")
    conn.close()


if __name__ == "__main__":
    main()
