"""Download a curated set of distinctive display fonts from Google Fonts and
self-host them so every MiniWeb site logo can use a different typeface with no
runtime network dependency.

Writes woff2 files to app/static/fonts/ and generates app/static/brand-fonts.css
(@font-face rules pointing at the local files). Run once with the miniweb python.
"""
import os
import re
import urllib.request

FONTS_DIR = "app/static/fonts"
CSS_OUT = "app/static/brand-fonts.css"

# (Google family name, weight/style spec for css2, local slug)
FAMILIES = [
    ("Pacifico", "", "pacifico"),
    ("Lobster", "", "lobster"),
    ("Righteous", "", "righteous"),
    ("Bungee", "", "bungee"),
    ("Monoton", "", "monoton"),
    ("Orbitron", ":wght@700", "orbitron"),
    ("Bebas Neue", "", "bebas-neue"),
    ("Abril Fatface", "", "abril-fatface"),
    ("Playfair Display", ":wght@800", "playfair-display"),
    ("Comfortaa", ":wght@700", "comfortaa"),
    ("Anton", "", "anton"),
    ("Rubik Mono One", "", "rubik-mono-one"),
    ("Caveat", ":wght@700", "caveat"),
    ("Sacramento", "", "sacramento"),
    ("Audiowide", "", "audiowide"),
    ("Shrikhand", "", "shrikhand"),
    ("Special Elite", "", "special-elite"),
    ("Kanit", ":wght@700", "kanit"),
    ("Archivo Black", "", "archivo-black"),
    ("Cinzel", ":wght@700", "cinzel"),
    ("Zilla Slab", ":wght@700", "zilla-slab"),
    ("Fredoka", ":wght@600", "fredoka"),
]

UA = ("Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0")


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=20) as r:
        return r.read()


def pick_latin_url(css_text):
    """Return the woff2 URL from the 'latin' unicode-range block (fallback: last)."""
    blocks = re.split(r"(?=/\*)", css_text)
    latin = None
    last = None
    for b in blocks:
        m = re.search(r"url\((https://[^)]+\.woff2)\)", b)
        if not m:
            continue
        last = m.group(1)
        if "/* latin */" in b:
            latin = m.group(1)
    return latin or last


def main():
    os.makedirs(FONTS_DIR, exist_ok=True)
    css_rules = ["/* Self-hosted brand fonts for MiniWeb site logos. Generated by scripts/fetch_brand_fonts.py */\n"]
    ok = 0
    for family, spec, slug in FAMILIES:
        q = family.replace(" ", "+") + spec
        url = f"https://fonts.googleapis.com/css2?family={q}&display=swap"
        try:
            css = fetch(url).decode("utf-8", "replace")
            font_url = pick_latin_url(css)
            if not font_url:
                print(f"  ! no woff2 for {family}")
                continue
            data = fetch(font_url)
            path = f"{FONTS_DIR}/{slug}.woff2"
            with open(path, "wb") as f:
                f.write(data)
            css_rules.append(
                f"@font-face{{font-family:'{family}';font-style:normal;font-display:swap;"
                f"src:url('/static/fonts/{slug}.woff2') format('woff2');}}"
            )
            ok += 1
            print(f"  ok {family} ({len(data)//1024} KB)")
        except Exception as e:
            print(f"  ! failed {family}: {e}")
    with open(CSS_OUT, "w") as f:
        f.write("\n".join(css_rules) + "\n")
    print(f"\nDownloaded {ok}/{len(FAMILIES)} fonts. Wrote {CSS_OUT}.")


if __name__ == "__main__":
    main()
