"""Database schema for map-services.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "locations": {
        "table_name": "map_services_locations",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("address", "TEXT NOT NULL DEFAULT ''"),
            ("lat", "REAL NOT NULL DEFAULT 0.0"),
            ("lng", "REAL NOT NULL DEFAULT 0.0"),
            ("phone", "TEXT NOT NULL DEFAULT ''"),
            ("hours", "TEXT NOT NULL DEFAULT ''"),
            ("rating", "REAL NOT NULL DEFAULT 0.0"),
        ],
        "indexes": [
            "category",
        ],
    },
    "routes": {
        "table_name": "map_services_routes",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("origin", "TEXT NOT NULL DEFAULT ''"),
            ("destination", "TEXT NOT NULL DEFAULT ''"),
            ("distance_km", "REAL NOT NULL DEFAULT 0.0"),
            ("duration_minutes", "INTEGER NOT NULL DEFAULT 0"),
            ("mode", "TEXT NOT NULL DEFAULT ''"),
            ("saved_date", "TEXT NOT NULL DEFAULT ''"),
            ("last_used", "TEXT NOT NULL DEFAULT ''"),
            ("use_count", "INTEGER NOT NULL DEFAULT 0"),
            ("steps", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "user_id",
        ],
    },
    "saved_places": {
        "table_name": "map_services_saved_places",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("location_id", "INTEGER NOT NULL DEFAULT 0"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("label", "TEXT NOT NULL DEFAULT ''"),
            ("address", "TEXT NOT NULL DEFAULT ''"),
            ("lat", "REAL NOT NULL DEFAULT 0.0"),
            ("lng", "REAL NOT NULL DEFAULT 0.0"),
            ("icon", "TEXT NOT NULL DEFAULT ''"),
            ("added_date", "TEXT NOT NULL DEFAULT ''"),
            ("visit_count", "INTEGER NOT NULL DEFAULT 0"),
            ("last_visited", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "user_id",
        ],
    },
    "search_history": {
        "table_name": "map_services_search_history",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("query", "TEXT NOT NULL DEFAULT ''"),
            ("timestamp", "TEXT NOT NULL DEFAULT ''"),
            ("result_selected", "TEXT NOT NULL DEFAULT ''"),
            ("result_address", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "timestamp",
            "user_id",
        ],
    },
    "users": {
        "table_name": "map_services_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("full_name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("phone", "TEXT NOT NULL DEFAULT ''"),
            ("home_address", "TEXT NOT NULL DEFAULT ''"),
            ("work_address", "TEXT NOT NULL DEFAULT ''"),
            ("default_mode", "TEXT NOT NULL DEFAULT ''"),
            ("units", "TEXT NOT NULL DEFAULT ''"),
            ("joined_date", "TEXT NOT NULL DEFAULT ''"),
            ("last_active", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "root_user_id",
        ],
    },
}
