"""Database schema for live.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "channel_points": {
        "table_name": "live_channel_points",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("channel_id", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("cost", "INTEGER NOT NULL DEFAULT 0"),
            ("is_enabled", "INTEGER NOT NULL DEFAULT 0"),
            ("max_per_stream", "INTEGER NOT NULL DEFAULT 0"),
        ],
    },
    "chat_messages": {
        "table_name": "live_chat_messages",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("stream_id", "TEXT NOT NULL DEFAULT ''"),
            ("user_id", "TEXT NOT NULL DEFAULT ''"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("message", "TEXT NOT NULL DEFAULT ''"),
            ("timestamp", "TEXT NOT NULL DEFAULT ''"),
            ("is_subscriber", "INTEGER NOT NULL DEFAULT 0"),
            ("badges", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "timestamp",
            "user_id",
        ],
    },
    "clips": {
        "table_name": "live_clips",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("stream_id", "TEXT NOT NULL DEFAULT ''"),
            ("channel_id", "TEXT NOT NULL DEFAULT ''"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("clipped_by", "TEXT NOT NULL DEFAULT ''"),
            ("clip_url", "TEXT NOT NULL DEFAULT ''"),
            ("thumbnail_url", "TEXT NOT NULL DEFAULT ''"),
            ("duration_seconds", "INTEGER NOT NULL DEFAULT 0"),
            ("views", "INTEGER NOT NULL DEFAULT 0"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("clipped_by_username", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "created_at",
        ],
    },
    "follows": {
        "table_name": "live_follows",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("follower_id", "TEXT NOT NULL DEFAULT ''"),
            ("channel_id", "TEXT NOT NULL DEFAULT ''"),
            ("followed_at", "TEXT NOT NULL DEFAULT ''"),
        ],
    },
    "streams": {
        "table_name": "live_streams",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("channel_id", "TEXT NOT NULL DEFAULT ''"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("category", "TEXT NOT NULL DEFAULT ''"),
            ("tags", "TEXT NOT NULL DEFAULT ''"),
            ("started_at", "TEXT NOT NULL DEFAULT ''"),
            ("ended_at", "TEXT NOT NULL DEFAULT ''"),
            ("duration_minutes", "INTEGER NOT NULL DEFAULT 0"),
            ("peak_viewers", "INTEGER NOT NULL DEFAULT 0"),
            ("average_viewers", "INTEGER NOT NULL DEFAULT 0"),
            ("total_views", "INTEGER NOT NULL DEFAULT 0"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
            ("vod_url", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "category",
            "status",
        ],
    },
    "subscriptions": {
        "table_name": "live_subscriptions",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("subscriber_id", "TEXT NOT NULL DEFAULT ''"),
            ("channel_id", "TEXT NOT NULL DEFAULT ''"),
            ("tier", "TEXT NOT NULL DEFAULT ''"),
            ("started_at", "TEXT NOT NULL DEFAULT ''"),
            ("renewed_at", "TEXT NOT NULL DEFAULT ''"),
            ("is_active", "INTEGER NOT NULL DEFAULT 0"),
            ("is_gift", "INTEGER NOT NULL DEFAULT 0"),
            ("months_subscribed", "INTEGER NOT NULL DEFAULT 0"),
            ("monthly_price_usd", "REAL NOT NULL DEFAULT 0.0"),
        ],
    },
    "users": {
        "table_name": "live_users",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("display_name", "TEXT NOT NULL DEFAULT ''"),
            ("channel_name", "TEXT NOT NULL DEFAULT ''"),
            ("avatar_url", "TEXT NOT NULL DEFAULT ''"),
            ("bio", "TEXT NOT NULL DEFAULT ''"),
            ("subscriber_count", "INTEGER NOT NULL DEFAULT 0"),
            ("total_views", "INTEGER NOT NULL DEFAULT 0"),
            ("is_partner", "INTEGER NOT NULL DEFAULT 0"),
            ("is_affiliate", "INTEGER NOT NULL DEFAULT 0"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("last_seen", "TEXT NOT NULL DEFAULT ''"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("channel_points_balance", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "created_at",
            "root_user_id",
            "status",
        ],
    },
}
