"""Database schema for project-homepages.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "project": {
        "table_name": "project_homepages_project",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("short_title", "TEXT NOT NULL DEFAULT ''"),
            ("venue", "TEXT NOT NULL DEFAULT ''"),
            ("year", "INTEGER NOT NULL DEFAULT 0"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
            ("doi", "TEXT NOT NULL DEFAULT ''"),
            ("arxiv_id", "TEXT NOT NULL DEFAULT ''"),
            ("authors", "TEXT NOT NULL DEFAULT ''"),
            ("sections", "TEXT NOT NULL DEFAULT ''"),
            ("keywords", "TEXT NOT NULL DEFAULT ''"),
            ("date_submitted", "TEXT NOT NULL DEFAULT ''"),
            ("date_accepted", "TEXT NOT NULL DEFAULT ''"),
            ("date_published", "TEXT NOT NULL DEFAULT ''"),
            ("last_updated", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "status",
        ],
    },
    "resources": {
        "table_name": "project_homepages_resources",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("type", "TEXT NOT NULL DEFAULT ''"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("url", "TEXT NOT NULL DEFAULT ''"),
            ("format", "TEXT NOT NULL DEFAULT ''"),
            ("size_mb", "REAL NOT NULL DEFAULT 0.0"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("date_added", "TEXT NOT NULL DEFAULT ''"),
            ("license", "TEXT NOT NULL DEFAULT ''"),
            ("duration_minutes", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "type",
        ],
    },
    "users": {
        "table_name": "project_homepages_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("full_name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("role", "TEXT NOT NULL DEFAULT ''"),
            ("affiliation", "TEXT NOT NULL DEFAULT ''"),
            ("department", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "department",
            "role",
            "root_user_id",
        ],
    },
}
