"""Database schema for academic-paper-db.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "papers": {
        "table_name": "academic_paper_db_papers",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("submitter", "TEXT NOT NULL DEFAULT ''"),
            ("authors", "TEXT NOT NULL DEFAULT ''"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("comments", "TEXT NOT NULL DEFAULT ''"),
            ("journal_ref", "TEXT NOT NULL DEFAULT ''"),
            ("doi", "TEXT NOT NULL DEFAULT ''"),
            ("report_no", "TEXT NOT NULL DEFAULT ''"),
            ("categories", "TEXT NOT NULL DEFAULT ''"),
            ("license", "TEXT NOT NULL DEFAULT ''"),
            ("abstract", "TEXT NOT NULL DEFAULT ''"),
            ("versions", "TEXT NOT NULL DEFAULT ''"),
            ("update_date", "TEXT NOT NULL DEFAULT ''"),
            ("authors_parsed", "TEXT NOT NULL DEFAULT ''"),
        ],
    },
    "users": {
        "table_name": "academic_paper_db_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("saved_papers", "TEXT NOT NULL DEFAULT ''"),
            ("followed_authors", "TEXT NOT NULL DEFAULT ''"),
            ("avatar", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "root_user_id",
        ],
    },
}
