"""Database schema for music.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "albums": {
        "table_name": "music_albums",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("artist_id", "INTEGER NOT NULL DEFAULT 0"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("release_date", "TEXT NOT NULL DEFAULT ''"),
            ("genre", "TEXT NOT NULL DEFAULT ''"),
            ("tracks_count", "INTEGER NOT NULL DEFAULT 0"),
            ("duration_minutes", "INTEGER NOT NULL DEFAULT 0"),
            ("cover_color", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "artist_id",
            "genre",
        ],
    },
    "artists": {
        "table_name": "music_artists",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("genre", "TEXT NOT NULL DEFAULT ''"),
            ("bio", "TEXT NOT NULL DEFAULT ''"),
            ("albums_count", "INTEGER NOT NULL DEFAULT 0"),
            ("monthly_listeners", "INTEGER NOT NULL DEFAULT 0"),
            ("verified", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "genre",
        ],
    },
    "library": {
        "table_name": "music_library",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("liked_tracks", "TEXT NOT NULL DEFAULT ''"),
            ("liked_albums", "TEXT NOT NULL DEFAULT ''"),
            ("followed_artists", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "user_id",
        ],
    },
    "playlists": {
        "table_name": "music_playlists",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("description", "TEXT NOT NULL DEFAULT ''"),
            ("track_ids", "TEXT NOT NULL DEFAULT ''"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("is_public", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "created_at",
            "user_id",
        ],
    },
    "tracks": {
        "table_name": "music_tracks",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("album_id", "INTEGER NOT NULL DEFAULT 0"),
            ("artist_id", "INTEGER NOT NULL DEFAULT 0"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("duration_seconds", "INTEGER NOT NULL DEFAULT 0"),
            ("track_number", "INTEGER NOT NULL DEFAULT 0"),
            ("plays", "INTEGER NOT NULL DEFAULT 0"),
            ("liked_by", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "album_id",
            "artist_id",
        ],
    },
    "users": {
        "table_name": "music_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("display_name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("avatar_color", "TEXT NOT NULL DEFAULT ''"),
            ("joined_date", "TEXT NOT NULL DEFAULT ''"),
            ("is_premium", "INTEGER NOT NULL DEFAULT 0"),
        ],
    },
}
