"""Database schema for remote-calls.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "messages": {
        "table_name": "remote_calls_messages",
        "columns": [
            ("meeting_id", "TEXT PRIMARY KEY"),
            ("msgs", "TEXT NOT NULL DEFAULT '[]'"),
        ],
    },
    "call_log": {
        "table_name": "remote_calls_call_log",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("caller_id", "TEXT NOT NULL DEFAULT ''"),
            ("callee_id", "TEXT NOT NULL DEFAULT ''"),
            ("type", "TEXT NOT NULL DEFAULT ''"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("duration_seconds", "INTEGER NOT NULL DEFAULT 0"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
            ("note", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "date",
            "status",
            "type",
        ],
    },
    "meetings": {
        "table_name": "remote_calls_meetings",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("host_id", "TEXT NOT NULL DEFAULT ''"),
            ("participants", "TEXT NOT NULL DEFAULT ''"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("duration_minutes", "INTEGER NOT NULL DEFAULT 0"),
            ("type", "TEXT NOT NULL DEFAULT ''"),
            ("recording_available", "INTEGER NOT NULL DEFAULT 0"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "date",
            "status",
            "type",
        ],
    },
    "recordings": {
        "table_name": "remote_calls_recordings",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("meeting_id", "TEXT NOT NULL DEFAULT ''"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("recorded_by", "TEXT NOT NULL DEFAULT ''"),
            ("date", "TEXT NOT NULL DEFAULT ''"),
            ("duration_minutes", "INTEGER NOT NULL DEFAULT 0"),
            ("file_size_mb", "REAL NOT NULL DEFAULT 0.0"),
            ("format", "TEXT NOT NULL DEFAULT ''"),
            ("download_url", "TEXT NOT NULL DEFAULT ''"),
            ("transcript_available", "INTEGER NOT NULL DEFAULT 0"),
            ("access", "TEXT NOT NULL DEFAULT ''"),
            ("views", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "date",
        ],
    },
    "users": {
        "table_name": "remote_calls_users",
        "columns": [
            ("id", "TEXT PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("display_name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("plan", "TEXT NOT NULL DEFAULT ''"),
            ("avatar_url", "TEXT NOT NULL DEFAULT ''"),
            ("timezone", "TEXT NOT NULL DEFAULT ''"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("last_login", "TEXT NOT NULL DEFAULT ''"),
            ("status", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "created_at",
            "root_user_id",
            "status",
        ],
    },
}
