"""MiniWeb Verifier Engine — executes verifier configs generated by Claude.

Each task's verifiers are organized per macro span. A verifier config is a JSON
object with a list of checks. Each check has a type and parameters.

Check types:
  grounding       — verify required URLs appear in the trajectory
  state_query     — query /_admin/data/ and assert a condition
  answer_match    — compare agent answer against expected value
  record_exists   — verify a record matching query exists
  record_absent   — verify no record matching query exists
  count_equals    — verify record count equals expected
  field_equals    — verify a specific field value
  action_performed — verify a specific action type exists in trajectory span

Result contract:
  {"pass": bool, "expected": any, "actual": any, "reason": str}
"""

import json
from annotation.normalizers import normalize


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def run_task_eval(verifier_configs, server_url="", flask_client=None,
                  trajectory=None, agent_answer="", request_log=None,
                  action_log=None):
    """Execute a list of per-macro verifier configs and return results.

    Args:
        verifier_configs: list of {macro, span, checks} dicts
        server_url: base URL for HTTP requests (unused if flask_client given)
        flask_client: Flask test client for querying /_admin/ endpoints
        trajectory: list of trajectory entries (actions + observations)
        agent_answer: the agent's final answer string
        request_log: list of HTTP request log entries from /_admin/log

    Returns:
        (all_passed: bool, results: list of {macro, pass, checks} dicts)
    """
    if trajectory is None:
        trajectory = []
    if request_log is None:
        request_log = []
    if action_log is None:
        action_log = []

    results = []
    for vc in verifier_configs:
        macro = vc.get("macro", "unknown")
        span = vc.get("span", [])
        checks = vc.get("checks", [])

        # Extract trajectory slice for this macro span
        span_trajectory = _get_span_trajectory(trajectory, span)

        macro_results = []
        for check in checks:
            r = _run_check(check, flask_client, span_trajectory, agent_answer, request_log, action_log)
            macro_results.append(r)

        all_pass = all(r["pass"] for r in macro_results) if macro_results else False
        results.append({
            "macro": macro,
            "span": span,
            "pass": all_pass,
            "checks": macro_results,
        })

    overall = all(r["pass"] for r in results) if results else False
    return overall, results


# ---------------------------------------------------------------------------
# Check dispatcher
# ---------------------------------------------------------------------------

def _run_check(check, client, span_trajectory, agent_answer, request_log=None, action_log=None):
    """Execute a single check and return a result dict."""
    ctype = check.get("type", "")
    desc = check.get("description", "")

    try:
        if ctype == "grounding":
            return _check_grounding(check, span_trajectory, desc, request_log, action_log)
        elif ctype == "state_query":
            return _check_state_query(check, client, desc)
        elif ctype == "answer_match":
            return _check_answer_match(check, agent_answer, desc)
        elif ctype == "record_exists":
            return _check_record_exists(check, client, desc)
        elif ctype == "record_absent":
            return _check_record_absent(check, client, desc)
        elif ctype == "count_equals":
            return _check_count_equals(check, client, desc)
        elif ctype == "field_equals":
            return _check_field_equals(check, client, desc)
        elif ctype == "action_performed":
            # Check beacon (action_log), request log, and trajectory — in that order
            return _check_action_performed(check, action_log or request_log or span_trajectory, desc)
        else:
            return _result(False, reason=f"Unknown check type: {ctype}", desc=desc)
    except Exception as e:
        return _result(False, reason=f"Check error: {e}", desc=desc)


# ---------------------------------------------------------------------------
# Check implementations
# ---------------------------------------------------------------------------

def _check_grounding(check, span_trajectory, desc, request_log=None, action_log=None):
    """Verify required URLs were visited. Checks trajectory, request log, and action beacon."""
    required = check.get("required_urls", [])
    if not required:
        return _result(True, desc=desc, reason="No URLs required")

    visited = set()
    # From trajectory (human annotator)
    for entry in span_trajectory:
        url = entry.get("url", "")
        if url:
            visited.add(url)

    # From server request log (agent-agnostic)
    if request_log:
        for entry in request_log:
            path = entry.get("path", "")
            if path:
                visited.add(path)

    # From action beacon log
    if action_log:
        for entry in action_log:
            url = entry.get("url", "")
            if url:
                visited.add(url)
            href = entry.get("href", "")
            if href:
                visited.add(href)

    missing = []
    for req_url in required:
        found = any(req_url in v or v.startswith(req_url) for v in visited)
        if not found:
            missing.append(req_url)

    if missing:
        return _result(False, expected=required, actual=list(visited)[:10],
                       reason=f"Missing pages: {missing}", desc=desc)
    return _result(True, expected=required, actual=list(visited)[:10],
                   reason="All required pages visited", desc=desc)


def _check_state_query(check, client, desc):
    """Query an API endpoint and assert a condition on the result.

    Accepts both /_admin/data/ paths and /sites/X/api/ paths.
    For /sites/ paths with POST method, replays the POST.
    """
    endpoint = check.get("endpoint", "")
    params = check.get("params", {})
    condition = check.get("check", "count_gt")
    expected = check.get("expected")
    method = check.get("method", "GET").upper()

    if not client or not endpoint:
        return _result(False, reason="No client or endpoint", desc=desc)

    if method == "POST":
        r = client.post(endpoint, json=params, content_type="application/json")
    else:
        r = client.get(endpoint, query_string=params)

    if r.status_code not in (200, 201, 302):
        return _result(False, reason=f"API returned {r.status_code} for {endpoint}", desc=desc)

    data = r.get_json()

    # Handle both list and dict responses
    if isinstance(data, list):
        actual_count = len(data)
        actual_value = data
    elif isinstance(data, dict):
        actual_count = data.get("count", len(data))
        actual_value = data
    else:
        actual_count = 0
        actual_value = data

    if condition == "count_gt":
        passed = actual_count > (expected or 0)
        return _result(passed, expected=f"count > {expected}", actual=actual_count,
                       reason=f"Count is {actual_count}", desc=desc)
    elif condition == "count_equals":
        passed = actual_count == expected
        return _result(passed, expected=f"count == {expected}", actual=actual_count,
                       reason=f"Count is {actual_count}", desc=desc)
    elif condition == "count_gte":
        passed = actual_count >= (expected or 0)
        return _result(passed, expected=f"count >= {expected}", actual=actual_count,
                       reason=f"Count is {actual_count}", desc=desc)
    elif condition == "equals":
        field = check.get("field", "")
        if field and isinstance(data, list) and data:
            actual_val = data[0].get(field)
        elif field and isinstance(data, dict):
            actual_val = data.get(field)
        else:
            actual_val = data
        passed = str(actual_val) == str(expected)
        return _result(passed, expected=expected, actual=actual_val,
                       reason=f"Field '{field}' = {actual_val}", desc=desc)
    elif condition == "contains":
        search = str(expected).lower()
        text = json.dumps(actual_value).lower()
        passed = search in text
        return _result(passed, expected=f"contains '{expected}'",
                       actual=f"({actual_count} records)",
                       reason="Found" if passed else "Not found", desc=desc)
    elif condition == "not_empty":
        passed = actual_count > 0
        return _result(passed, expected="not empty", actual=actual_count,
                       reason=f"Count is {actual_count}", desc=desc)
    else:
        return _result(False, reason=f"Unknown condition: {condition}", desc=desc)


def _check_answer_match(check, agent_answer, desc):
    """Compare agent answer against expected value using normalizers.

    match_mode:
      exact    — normalized values must be equal
      fuzzy    — normalized values must be equal (same as exact, uses normalizer)
      includes — expected text must appear within the answer
    """
    expected = check.get("expected", "")
    match_type = check.get("match_type", "string")
    match_mode = check.get("match_mode", "exact")
    alternatives = check.get("alternatives", [])

    if match_mode == "includes":
        # Substring check (case-insensitive)
        passed = expected.lower() in agent_answer.lower()
        return _result(passed, expected=expected, actual=agent_answer,
                       reason=f"Answer {'includes' if passed else 'does not include'} '{expected}'",
                       desc=desc)

    if match_mode == "fuzzy":
        # LLM judges whether the answers are semantically equivalent
        from app.llm import call_llm
        prompt = (
            f'Are these two answers to a web task the same? '
            f'Consider formatting differences (e.g., "$5" vs "5", "3 items" vs "3") as equivalent.\n\n'
            f'Expected: "{expected}"\n'
            f'Actual: "{agent_answer}"\n\n'
            f'Reply with ONLY "yes" or "no".'
        )
        result = call_llm(prompt, max_tokens=5, temperature=0)
        passed = result and result.strip().lower().startswith("yes")
        return _result(passed, expected=expected, actual=agent_answer,
                       reason=f"LLM judge: {'equivalent' if passed else 'different'}",
                       desc=desc)

    # exact — use normalizers
    norm_answer = normalize(agent_answer, match_type)
    norm_expected = normalize(expected, match_type)

    if norm_answer == norm_expected:
        return _result(True, expected=expected, actual=agent_answer,
                       reason="Answer matches", desc=desc)

    # Check alternatives
    for alt in alternatives:
        if normalize(alt, match_type) == norm_answer:
            return _result(True, expected=expected, actual=agent_answer,
                           reason=f"Matches alternative: {alt}", desc=desc)

    return _result(False, expected=expected, actual=agent_answer,
                   reason=f"Expected '{expected}', got '{agent_answer}'", desc=desc)


def _check_record_exists(check, client, desc):
    """Verify a record matching query exists."""
    endpoint = check.get("endpoint", "")
    params = check.get("params", {})

    if not client or not endpoint:
        return _result(False, reason="No client or endpoint", desc=desc)

    r = client.get(endpoint, query_string=params)
    data = r.get_json() if r.status_code == 200 else []
    count = len(data) if isinstance(data, list) else (1 if data else 0)

    return _result(count > 0, expected="record exists", actual=count,
                   reason=f"{count} record(s) found", desc=desc)


def _check_record_absent(check, client, desc):
    """Verify no record matching query exists."""
    endpoint = check.get("endpoint", "")
    params = check.get("params", {})

    if not client or not endpoint:
        return _result(False, reason="No client or endpoint", desc=desc)

    r = client.get(endpoint, query_string=params)
    data = r.get_json() if r.status_code == 200 else []
    count = len(data) if isinstance(data, list) else (1 if data else 0)

    return _result(count == 0, expected="record absent", actual=count,
                   reason=f"{count} record(s) found", desc=desc)


def _check_count_equals(check, client, desc):
    """Verify record count equals expected."""
    endpoint = check.get("endpoint", "")
    params = check.get("params", {})
    expected = check.get("expected", 0)

    if not client or not endpoint:
        return _result(False, reason="No client or endpoint", desc=desc)

    # Use _count param if available
    count_params = {**params, "_count": "1"}
    r = client.get(endpoint, query_string=count_params)
    data = r.get_json() if r.status_code == 200 else {}

    if isinstance(data, dict) and "count" in data:
        actual = data["count"]
    elif isinstance(data, list):
        actual = len(data)
    else:
        actual = 0

    return _result(actual == expected, expected=expected, actual=actual,
                   reason=f"Count: {actual}", desc=desc)


def _check_field_equals(check, client, desc):
    """Verify a specific field value on a record."""
    endpoint = check.get("endpoint", "")
    params = check.get("params", {})
    field = check.get("field", "")
    expected = check.get("expected")

    if not client or not endpoint or not field:
        return _result(False, reason="Missing endpoint or field", desc=desc)

    r = client.get(endpoint, query_string=params)
    data = r.get_json() if r.status_code == 200 else []

    if isinstance(data, list) and data:
        actual = data[0].get(field)
    elif isinstance(data, dict):
        actual = data.get(field)
    else:
        actual = None

    passed = str(actual) == str(expected)
    return _result(passed, expected=expected, actual=actual,
                   reason=f"Field '{field}' = {actual}", desc=desc)


def _check_action_performed(check, log_entries, desc):
    """Verify an action was performed.

    Checks two types of evidence:
    1. Request log (/_admin/log): HTTP method + path + params
    2. Action beacon (/_admin/beacon): UI action + target + value

    Both work identically for human annotators and browser agents.
    """
    log = log_entries if isinstance(log_entries, list) else []

    # Mode 1: Request-log check (method + path + params)
    method = check.get("method", "")
    path = check.get("path", "")
    param_key = check.get("param_key", "")
    param_value = check.get("param_value", "")

    if method and path:
        for entry in log:
            entry_method = entry.get("method", "").upper()
            entry_path = entry.get("path", "") or entry.get("url", "") or ""
            if entry_method != method.upper():
                continue
            if path not in entry_path:
                continue
            if param_key and param_value:
                req_params = entry.get("query", {})
                req_body = entry.get("body", {})
                found_val = str(req_params.get(param_key, "")) or str(req_body.get(param_key, ""))
                if param_value.lower() not in found_val.lower():
                    continue
            expected = f"{method} {path}"
            if param_key:
                expected += f" ({param_key}={param_value})"
            return _result(True, expected=expected, actual=entry_path,
                           reason="Request found in server log", desc=desc)

        expected = f"{method} {path}"
        if param_key:
            expected += f" ({param_key}={param_value})"
        return _result(False, expected=expected, actual="(not in log)",
                       reason="Request not found", desc=desc)

    # Mode 2: Beacon/trajectory check (action + target + value)
    required_action = check.get("action", "")
    target_contains = check.get("target_contains", "")
    value_equals = check.get("value_equals", "")

    import re as _re
    if not value_equals and target_contains:
        m = _re.search(r"=\s*['\"](.+?)['\"]$", target_contains)
        if m:
            value_equals = m.group(1)
            target_contains = target_contains[:m.start()].strip()

    for entry in log:
        entry_action = entry.get("action", "")
        if entry.get("type") == "action":
            entry_action = entry.get("action", "")
        if not entry_action or entry_action != required_action:
            continue
        entry_target = (entry.get("target", "") or "").lower()
        if target_contains and target_contains.lower() not in entry_target:
            continue
        if value_equals:
            actual_value = entry.get("option_text") or entry.get("text") or entry.get("value") or ""
            target_val = _re.search(r"=\s*['\"](.+?)['\"]$", entry.get("target", "") or "")
            if target_val:
                actual_value = actual_value or target_val.group(1)
            if str(actual_value).strip().lower() != str(value_equals).strip().lower():
                continue
        return _result(True, expected=required_action, actual=entry.get("target"),
                       reason="Action found in beacon log", desc=desc)

    return _result(False, expected=required_action or method, actual="(not found)",
                   reason="Action not found in any log", desc=desc)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _get_span_trajectory(trajectory, span):
    """Extract trajectory entries for a macro span [start, end]."""
    if not span or len(span) < 2:
        return trajectory

    start, end = span
    # Action indices are 1-based; trajectory entries include both actions and observations
    result = []
    action_idx = 0
    for entry in trajectory:
        if entry.get("type") == "action":
            action_idx += 1
            if start <= action_idx <= end:
                result.append(entry)
        elif entry.get("type") == "observation":
            if start <= action_idx <= end:
                result.append(entry)
    return result


def _result(passed, expected=None, actual=None, reason="", desc=""):
    """Construct a standard result dict."""
    return {
        "pass": passed,
        "expected": expected,
        "actual": actual,
        "reason": reason,
        "description": desc,
    }
