"""Database schema for qa-knowledge.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "answers": {
        "table_name": "qa_knowledge_answers",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("question_id", "INTEGER NOT NULL DEFAULT 0"),
            ("author_root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("body_excerpt", "TEXT NOT NULL DEFAULT ''"),
            ("score", "INTEGER NOT NULL DEFAULT 0"),
            ("is_accepted", "INTEGER NOT NULL DEFAULT 0"),
            ("creation_date", "TEXT NOT NULL DEFAULT ''"),
            ("body", "TEXT NOT NULL DEFAULT ''"),
            ("owner_id", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "owner_id",
        ],
    },
    "questions": {
        "table_name": "qa_knowledge_questions",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("body_excerpt", "TEXT NOT NULL DEFAULT ''"),
            ("author_root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("tags", "TEXT NOT NULL DEFAULT ''"),
            ("score", "INTEGER NOT NULL DEFAULT 0"),
            ("answer_count", "INTEGER NOT NULL DEFAULT 0"),
            ("site", "TEXT NOT NULL DEFAULT ''"),
            ("creation_date", "TEXT NOT NULL DEFAULT ''"),
            ("body", "TEXT NOT NULL DEFAULT ''"),
            ("accepted_answer_id", "TEXT NOT NULL DEFAULT ''"),
            ("owner_id", "TEXT NOT NULL DEFAULT ''"),
            ("view_count", "INTEGER NOT NULL DEFAULT 0"),
        ],
        "indexes": [
            "owner_id",
            "creation_date",
            "score",
        ],
    },
    "tags_meta": {
        "table_name": "qa_knowledge_tags_meta",
        "columns": [
            ("tag", "TEXT PRIMARY KEY"),
            ("count", "INTEGER NOT NULL DEFAULT 0"),
        ],
    },
    "users": {
        "table_name": "qa_knowledge_users",
        "columns": [
            ("row_id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("se_username", "TEXT NOT NULL DEFAULT ''"),
            ("se_display_name", "TEXT NOT NULL DEFAULT ''"),
            ("reputation", "INTEGER NOT NULL DEFAULT 0"),
            ("tags", "TEXT NOT NULL DEFAULT ''"),
            ("top_answers_count", "INTEGER NOT NULL DEFAULT 0"),
            ("member_since", "TEXT NOT NULL DEFAULT ''"),
            ("about_me", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "root_user_id",
        ],
    },
}
