"""Database schema for documents.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "documents": {
        "table_name": "documents_documents",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("title", "TEXT NOT NULL DEFAULT ''"),
            ("content", "TEXT NOT NULL DEFAULT ''"),
            ("owner_id", "INTEGER NOT NULL DEFAULT 0"),
            ("folder_id", "INTEGER NOT NULL DEFAULT 0"),
            ("collaborators", "TEXT NOT NULL DEFAULT ''"),
            ("word_count", "INTEGER NOT NULL DEFAULT 0"),
            ("is_starred", "INTEGER NOT NULL DEFAULT 0"),
            ("is_trashed", "INTEGER NOT NULL DEFAULT 0"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
            ("updated_at", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "created_at",
            "owner_id",
            "updated_at",
        ],
    },
    "folders": {
        "table_name": "documents_folders",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("owner_id", "INTEGER NOT NULL DEFAULT 0"),
            ("color", "TEXT NOT NULL DEFAULT ''"),
            ("created_at", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "created_at",
            "owner_id",
        ],
    },
    "revisions": {
        "table_name": "documents_revisions",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("document_id", "INTEGER NOT NULL DEFAULT 0"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("timestamp", "TEXT NOT NULL DEFAULT ''"),
            ("summary", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "timestamp",
            "user_id",
        ],
    },
    "users": {
        "table_name": "documents_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("root_user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
            ("avatar_color", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "root_user_id",
        ],
    },
}
