"""Database schema for translation.

Auto-generated by scripts/generate_schemas.py — edit freely.
"""

TABLES = {
    "glossaries": {
        "table_name": "translation_glossaries",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("source_lang", "TEXT NOT NULL DEFAULT ''"),
            ("target_lang", "TEXT NOT NULL DEFAULT ''"),
            ("entries", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "user_id",
        ],
    },
    "history": {
        "table_name": "translation_history",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("source_lang", "TEXT NOT NULL DEFAULT ''"),
            ("target_lang", "TEXT NOT NULL DEFAULT ''"),
            ("source_text", "TEXT NOT NULL DEFAULT ''"),
            ("translated_text", "TEXT NOT NULL DEFAULT ''"),
            ("timestamp", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "timestamp",
            "user_id",
        ],
    },
    "languages": {
        "table_name": "translation_languages",
        "columns": [
            ("row_id", "INTEGER PRIMARY KEY"),
            ("code", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("native_name", "TEXT NOT NULL DEFAULT ''"),
        ],
    },
    "saved": {
        "table_name": "translation_saved",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("user_id", "INTEGER NOT NULL DEFAULT 0"),
            ("source_lang", "TEXT NOT NULL DEFAULT ''"),
            ("target_lang", "TEXT NOT NULL DEFAULT ''"),
            ("source_text", "TEXT NOT NULL DEFAULT ''"),
            ("translated_text", "TEXT NOT NULL DEFAULT ''"),
            ("label", "TEXT NOT NULL DEFAULT ''"),
        ],
        "indexes": [
            "user_id",
        ],
    },
    "settings": {
        "table_name": "translation_settings",
        "columns": [
            ("row_id", "INTEGER PRIMARY KEY"),
            ("_1", "TEXT NOT NULL DEFAULT ''"),
            ("_2", "TEXT NOT NULL DEFAULT ''"),
            ("_3", "TEXT NOT NULL DEFAULT ''"),
            ("_4", "TEXT NOT NULL DEFAULT ''"),
            ("_5", "TEXT NOT NULL DEFAULT ''"),
        ],
    },
    "users": {
        "table_name": "translation_users",
        "columns": [
            ("id", "INTEGER PRIMARY KEY"),
            ("username", "TEXT NOT NULL DEFAULT ''"),
            ("password", "TEXT NOT NULL DEFAULT ''"),
            ("name", "TEXT NOT NULL DEFAULT ''"),
            ("email", "TEXT NOT NULL DEFAULT ''"),
        ],
    },
}
